### ISSUE TITLE
Iteration Plan for June 2019

### ISSUE THREAD

**Issue by lukekim** [dapr/dapr#1]
This plan captures our work in **June**. This is a 2-week iteration. We will **ship** our June Update in **early July**.

## Theme

- Being the very first Plan, we'll focus on putting the process and logistics in place to ship a release.
- Customer ready demo to show the capabilities of Actions

## Endgame

June 24th, 2019: Endgame begins
July 2nd, 2019: Endgame complete 

The endgame details for this iteration are tracked [#2](https://github.com/actionscore/actions/issues/2)

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

|Mark | Description|
|-- | --|
|🏃 | work in progress|
|✋ | blocked task|
|💪 | stretch goal for this iteration|
|🔴 | missing issue reference|
|🔵 | more investigation required to remove uncertainty|
|⚫️ | under discussion within the team|

### Runtime

- [ ] Create basic test cases for components @Haishi2016 [#9](https://github.com/actionscore/actions/issues/9)
  - **Moved to July 2019 iteration**
- [x] Update Readme.md diagrams @likamrat [#5](https://github.com/actionscore/actions/issues/5)

### Demo/Sample

- [x] Create samples @Haishi2016 @yaron2 [#7](https://github.com/actionscore/actions/issues/7)

### Engineering Systems

- [x] Import code @yaron2 [#4](https://github.com/actionscore/actions/issues/4)
- [x] Import demo app code @yaron2  [#6](https://github.com/actionscore/actions/issues/6)
- [x] Create Makefiles @yaron2 [#8](https://github.com/actionscore/actions/issues/8)
- [x] Setup CI @lukekim [#3](https://github.com/actionscore/actions/issues/3)
