### ISSUE TITLE
Milestone 0.4.0 Endgame

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#1029]
## Schedule

End game master: @yaron2   
End game buddy: @msfussell 

This is the schedule for the 0.4.0 Release.

Special note: this release contains breaking changes in the API and introduces new functionality.
As such, in addition to the regular release notes that come out, it is important to have an item below that covers breaking changes and how to deal with them.

02/06  **12pm** PST code freeze for the release<br>
02/13 Release date

- [x] Code freeze at 12pm 02/06
- [x] Create 0.4.0-rc release branches for Dapr runtime @youngbupark 
- [x] Create 0.4.0-rc release branches for CLI @youngbupark 
- [x] Test and validate the release - run through samples, demos, review docs, E2E tests, manual testing, @yaron2 @Haishi2016 @amanbha @youngbupark @LMWF @msfussell @pruthvidhodda 
- [x] Test and validate the .NET SDK release v0.4.0-preview01 - run through samples, @amanbha 
- [x] Test and validate the .Java SDK release v0.2.0-rc-1 - run through integration tests and samples, @artursouza 
- [x] Fix bugs
- [x] Create 0.4.0-preview01 .NET SDK @amanbha @LMWF
- [x] Create 0.2.0-rc-1 Java SDK @artursouza @LMWF
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK @yaron2 
- [x] Verify breaking changes section in release notes @yaron2 
- [x] Create 0.4.0 release branches for Dapr runtime @youngbupark @yaron2 
- [x] Create 0.4.0 release branches for CLI @artursouza @yaron2 
- [x] Update Helm Charts @yaron2 
- [x] Manually upload Nuget packages. - @LMWF @amanbha
- [x] Create 0.4.0 tag for docs and samples in the repos. @youngbupark @yaron2
- [x] Generate new Java docs based on the release version of the Java SDK and push to master. @artursouza 
- [x] Update Java SDK's README.md to refer to latest version. @artursouza 
- [x] Release sample Docker images to GitHub artifacts @youngbupark @yaron2 
- [x] Validate that the Release runtime images are pushed to Docker Hub @yaron2 @youngbupark
- [x] Update latest kubernetes install YAML for `dapr init --kubernetes`
- [x] Announcement email and Twitter post @msfussell

**Comment by youngbupark** [comment]
Breaking changes:
1) helm change from v2 to v3
2) support multi statestore api

**Comment by youngbupark** [comment]
Merge this pr - https://github.com/dapr/samples/pull/152 once we cut sample version.

cc/ @pruthvidhodda

**Comment by youngbupark** [comment]
Version update in docs - https://github.com/dapr/docs/pull/352

**Comment by mkosieradzki** [comment]
Hi, I don't see pushing updated helm chart on the task list... and obviously the previous one doesn't deploy the sentry - and despite containers are pushed to dockerhub helm chart is not pushed to the ACR.

**Comment by yaron2** [comment]
> Hi, I don't see pushing updated helm chart on the task list... and obviously the previous one doesn't deploy the sentry - and despite containers are pushed to dockerhub helm chart is not pushed to the ACR.

Normally we do this as part of the branch release which pushes the images. I updated with its own bullet..

**Comment by yaron2** [comment]
Done!
