### ISSUE TITLE
v0.5.0 Milestone Plan

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#1074]
*Milestone Master:* @LMWF 
*Milestone Buddy:* TBD

## Key scenarios for this milestone 

* [x] Address priority reported bugs
* [x] Improve Dapr Observability
    - https://github.com/dapr/dapr/issues/969
    - https://github.com/dapr/dapr/issues/945
* [x] Secrets Building Block API 
    - https://github.com/dapr/dapr/issues/1084
    - https://github.com/dapr/dapr/issues/1034
* [x] Simplification of the .NET Client API https://github.com/dapr/dotnet-sdk/issues/226
* [x] Strongly typed Java actors https://github.com/dapr/java-sdk/issues/241

### Release date - 12th March

Legend of annotations:

|Mark | Description|
|------|-----------|
| 🏃 | work in progress|
| ✋ | blocked task|
| 💪 | stretch goal for this iteration|
| 🔴 | missing issue reference|
| 🔵 | more investigation required to remove uncertainty|
| ⚫️ | under discussion within the team|
