### ISSUE TITLE
Milestone 0.5.0 Endgame

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1243]
## Schedule

End game master: @youngbupark 
End game buddy: @yaron2 

This is the schedule for the 0.5.0 Release

03/10  **02:30pm** PST code freeze for the release
03/12 Release date

- [x] Code freeze at 02:30pm 3/10
- [x] No P0 issues before code freeze.
- [x] Create 0.5.0-rc release branches for Dapr runtime @youngbupark 
- [x] Create 0.5.0-rc release branches for CLI @youngbupark 
- [x] Test and validate the release - run through samples, demos, review docs, E2E tests, manual testing, @yaron2 @Haishi2016 @amanbha @youngbupark @LMWF @msfussell @pruthvidhodda 
- [x] Fix bugs
- [x] Test and validate the .NET SDK release v0.5.0-preview01 - run through samples, @amanbha 
- [x] Test and validate the .Java SDK release v0.3.0-rc-2 - run through integration tests and samples, @artursouza 
- [x] Create 0.5.0-preview01 .NET SDK @amanbha @LMWF
- [x] Create 0.3.0-rc-1Java SDK @artursouza @LMWF
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK @yaron2 
- [x] Verify breaking changes section in release notes @yaron2 
- [x] Create 0.5.0 release branches for Dapr runtime @youngbupark @yaron2 
- [x] Create 0.5.0 release branches for CLI @artursouza @yaron2 
- [x] Update Helm Charts @yaron2 
- [x] Manually upload Nuget packages. - @LMWF @amanbha
- [x] Review Grafana dashboard and write the doc for monitoring onboarding @youngbupark @shalabhms 
- [x] Create 0.5.0 tag for docs and samples in the repos. @youngbupark @yaron2
- [x] Generate new Java docs based on the release version of the Java SDK and push to master. @artursouza 
- [x] Update Java SDK's README.md to refer to latest version. @artursouza 
- [x] Release sample Docker images to GitHub artifacts @youngbupark @yaron2 
- [x] Validate that the Release runtime images are pushed to Docker Hub @yaron2 @youngbupark
- [x] Update latest kubernetes install YAML for `dapr init --kubernetes` @yaron2 
- [x] Announcement email and Twitter post @msfussell
