### ISSUE TITLE
v0.6.0 Milestone Plan

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#1295]
*Milestone Master:* @pruthvidhodda 
*Milestone Buddy:* TBD

## Key scenarios for this milestone 

* [x] Address priority reported bugs
* [x] Priority Features
    -  Support Redis with SSL, e.g. for Azure Managed Redis Cache #213
* [x] Continue  Dapr Observability improvement
    - https://github.com/dapr/dapr/issues/969
    - https://github.com/dapr/dapr/issues/945
* [x] Long Hauls Tests
* [x] E2E Tests 
* [x] Security

### Release date - 2nd April

Legend of annotations:

|Mark | Description|
|------|-----------|
| 🏃 | work in progress|
| ✋ | blocked task|
| 💪 | stretch goal for this iteration|
| 🔴 | missing issue reference|
| 🔵 | more investigation required to remove uncertainty|
| ⚫️ | under discussion within the team|
