### ISSUE TITLE
Milestone 0.6.0 Endgame

### ISSUE THREAD

**Issue by shalabhms** [dapr/dapr#1346]
## Schedule

End game master: @shalabhms 
End game buddy: @youngbupark 

This is the schedule for the 0.6.0 Release

03/31  **12:00pm** PST code freeze for the release
04/02 Release date

- [x] Code freeze at 12:00pm 3/31
- [x] No P0 issues before code freeze.
- [x] Create 0.6.0-rc release branches for Dapr runtime @shalabhms  
- [x] Create 0.6.0-rc release branches for CLI @shalabhms
- [x] Test and validate the release - run through samples, demos, review docs, E2E tests, manual testing, @yaron2 @Haishi2016 @amanbha @shalabhms @youngbupark @LMWF @msfussell @pruthvidhodda 
- [x] Share 0.6.0-rc release with Azure Tools team to test VS Code and Remote Containers - Phil Hoff
- [x] Fix bugs
- [x] Test and validate the .NET SDK release v0.6.0-preview01 - run through samples, @LMWF @amanbha 
- [x] Test and validate the .Java SDK release v0.4.0-rc-1 - run through integration tests and samples, @artursouza 
- [x] Create 0.6.0-preview01 .NET SDK @amanbha @LMWF
- [x] Create 0.4.0-rc-1 Java SDK @artursouza @LMWF
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK @youngbupark  
- [x] Verify breaking changes section in release notes @youngbupark  
- [x] Create 0.6.0 release branches for Dapr runtime @shalabhms 
- [x] Create 0.6.0 release branches for CLI @shalabhms 
- [x] Update Helm Charts @yaron2  
- [x] Upload Nuget packages. - @LMWF @amanbha
- [x] Create 0.6.0 tag for docs in the repos. @shalabhms @youngbupark 
- [x] Update version tag in the images and then create 0.6.0 tag for samples in the repos. @shalabhms @youngbupark 
- [ ] Generate new Java docs based on the release version of the Java SDK and push to master. @artursouza 
- [ ] Update Java SDK's README.md to refer to latest version. @artursouza 
- [x] Validate latest kubernetes install YAML for `dapr init --kubernetes` @yaron2 
- [x] Announcement email and Twitter post @msfussell
