### ISSUE TITLE
v0.7.0 Milestone Plan

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#1374]
*Milestone Master:* @shalabhms 
*Milestone Buddy:* @TBD

## Key scenarios for this milestone 

* [x] Address priority bugs
[All bugs](https://github.com/dapr/dapr/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fbug)
[P1 bugs](https://github.com/dapr/dapr/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fbug+label%3Ap1)

* [x] Address customer features

* [x] [Continue Observability](https://github.com/dapr/dapr/issues?q=is%3Aissue+label%3Akind%2Fobservability+is%3Aopen+)

* [x] [Continue Long Hauls & E2E Tests](https://github.com/dapr/dapr/labels/area%2Ftest%2Fe2e)

* [x] [Continue Security](https://github.com/dapr/dapr/issues?q=is%3Aissue+label%3Akind%2Fsecurity+is%3Aopen)

* [x] [Start Perf and Scale](https://github.com/orgs/dapr/projects/26)

### Release date - 5th May

Legend of annotations:

|Mark | Description|
|------|-----------|
| 🏃 | work in progress|
| ✋ | blocked task|
| 💪 | stretch goal for this iteration|
| 🔴 | missing issue reference|
| 🔵 | more investigation required to remove uncertainty|
| ⚫️ | under discussion within the team|
