### ISSUE TITLE
Milestone 0.7.0 Endgame

### ISSUE THREAD

**Issue by shalabhms** [dapr/dapr#1455]
## Schedule

End game master: @shalabhms 
End game buddy: @pruthvidhodda 

This is the schedule for the 0.7.0 Release

05/01  **09:00 AM** PST code freeze for the release
05/05 Release date

- [x] Code freeze at 09:00 am 05/01
- [x] No P0 issues before code freeze.
- [x] Create 0.7.0 release branches for Dapr runtime @shalabhms  
- [x] Create 0.7.0 release branches for CLI @shalabhms
- [x] Cut the 0.7.0 rc release for Dapr runtime @shalabhms  
- [x] Cut the 0.7.0 rc re;ease for CLI @shalabhms
- [x] Test and validate the release - run through samples, demos, review docs, E2E tests, manual testing, @yaron2 @Haishi2016 @amanbha @shalabhms @youngbupark @LMWF @msfussell @pruthvidhodda 
- [x] Share 0.7.0-rc release with Azure Tools team to test VS Code and Remote Containers - Phil Hoff
- [x] Fix bugs
- [x] Test and validate the .NET SDK release v0.7.0-preview01 - run through samples, @LMWF
- [x] Test and validate the .Java SDK release v0.5.0-rc-1 - run through integration tests and samples, @artursouza 
- [x] Create 0.7.0-preview01 .NET SDK @amanbha @LMWF
- [x] Create 0.5.0-rc-1 Java SDK @artursouza @LMWF
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK . Checked them in release branch before cutting the release.@yaron2 
- [x] Verify breaking changes section in release notes @youngbupark  
- [x] Update Helm Charts in release branch before cutting the release @yaron2  
- [x] Upload Nuget packages. - @LMWF @amanbha
- [x] Create 0.7.0 tag for docs in the repos. @shalabhms @youngbupark 
- [x] Create release-0.7.0 branch for samples, update version tag in the images, create v0.7.0 tag and update the readme in master @shalabhms @youngbupark @pruthvidhodda
- [x] Generate new Java docs based on the release version of the Java SDK and push to master. @artursouza 
- [x] Update Java SDK's README.md to refer to latest version. @artursouza 
- [x] Validate latest kubernetes install YAML for `dapr init --kubernetes` @yaron2 
- [x] Announcement email and Twitter post @msfussell
