### ISSUE TITLE
v0.8.0 Milestone Plan

### ISSUE THREAD

**Issue by orizohar** [dapr/dapr#1525]
*Milestone Master:* @youngbupark 
*Milestone Buddy:* @wcs1only 

## Key scenarios for this milestone 

* [x] Address priority bugs
[All bugs](https://github.com/dapr/dapr/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fbug)
[P1 bugs](https://github.com/dapr/dapr/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fbug+label%3Ap1)

* [x] Address customer features

* [x] [Bi-directional binding](https://github.com/dapr/dapr/issues/1116)

* [x] [Custom Pub sub routes](https://github.com/dapr/dapr/issues/1518)

* [x] [Finish Observability](https://github.com/dapr/dapr/issues?q=is%3Aissue+label%3Akind%2Fobservability+is%3Aopen+)

* [ ] [Continue Long Hauls & E2E Tests](https://github.com/dapr/dapr/labels/area%2Ftest%2Fe2e)

* [ ] [Continue Security](https://github.com/dapr/dapr/issues?q=is%3Aissue+label%3Akind%2Fsecurity+is%3Aopen)

### Release date - 9th June 2020

Legend of annotations:

|Mark | Description|
|------|-----------|
| 🏃 | work in progress|
| ✋ | blocked task|
| 💪 | stretch goal for this iteration|
| 🔴 | missing issue reference|
| 🔵 | more investigation required to remove uncertainty|
| ⚫️ | under discussion within the team|
