### ISSUE TITLE
0.7.1 Patch Checklist

### ISSUE THREAD

**Issue by shalabhms** [dapr/dapr#1547]
- [x] Push tag for 0.7.1 for  0.7.0 release branch for Dapr runtime @shalabhms 
- [x] Test and validate the release - run through samples @shalabhms 
- [x] Fix bugs
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) -Dapr, . Checked them in release branch before cutting the release.@shalabhms
- [x] Update Helm Charts in release branch before cutting the release @shalabhms 
- [ ] Not applicable .No change in the doc so need to confirm if we need this item. Create 0.7.1 tag for docs in the repos. @shalabhms 
- [ ] Not applicable. No change in the samples so need to confirm if we need this item. Create v0.7.1 tag and update the readme in master @shalabhms 
- [x] Validate latest kubernetes install YAML for `dapr init --kubernetes` @youngbupark 
- [x] Upload Helm chart
