### ISSUE TITLE
Milestone 0.8.0 Endgame

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1619]
## Schedule

End game master: @wcs1only 
End game buddy: @vinayada1 @youngp 

This is the schedule for the 0.8.0 Release

06/05  **01:40 PM** PST code freeze for the release
06/09 Release date

- [x] Code freeze at 01:00 pm 06/05
- [x] No P0 issues before code freeze.
- [x] Create 0.1.0 relese branch for component-contrib @youngbupark 
- [x] Cut 0.1.0 releae for component-contrib @youngbupark 
- [x] update component-contrib pkg to 0.1.0 in dpar/dapr
- [x] Create 0.8.0 release branches for Dapr runtime @youngbupark   
- [x] Create 0.8.0 release branches for CLI @youngbupark
- [x] Cut the 0.8.0 rc release for Dapr runtime @youngbupark  
- [x] Cut the 0.8.0 rc release for CLI @youngbupark
- [x] Test and validate samples - @pruthvidhodda @vinayada1 @wcs1only @mukundansundar 
- [x] Test and validate the release - run through demos, review docs, E2E tests, manual testing, @yaron2 @Haishi2016 @amanbha @shalabhms @youngbupark @LMWF @msfussell @pruthvidhodda 
- [x] Share 0.8.0-rc release with Azure Tools team to test VS Code and Remote Containers - Phil Hoff
- [x] Create release-0.2 for workflow - @yaron2 
- [x] Create 0.2.0-rc.0 tag for workflow - @yaron2 
- [x] Test 0.2.0-rc.0 for workflow - @yaron2 
- [x] Fix bugs
- [x] Test and validate the .NET SDK release v0.8.0-preview01 - run through samples, @LMWF
- [x] Test and validate the .Java SDK release v0.6.0-rc-1 - run through integration tests and samples, @artursouza 
- [x] Create 0.8.0-preview01 .NET SDK @amanbha @LMWF
- [x] Create 0.6.0-rc-1 Java SDK @artursouza @LMWF
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK . Checked them in release branch before cutting the release.@yaron2 
- [x] Verify breaking changes section in release notes @youngbupark  
- [x] Update Helm Charts in release branch before cutting the release @vinayada1 
- [x] Upload Nuget packages. - @LMWF @amanbha
- [x] Create 0.8.0 tag for docs in the repos. @shalabhms @youngbupark 
- [x] Create release-0.8.0 branch for samples, update version tag in the images, create v0.7.0 tag and update the readme in master @shalabhms @youngbupark @pruthvidhodda
- [x] Upload new helm chart to ACR @yaron2 
- [x] Generate new Java docs based on the release version of the Java SDK and push to master. @artursouza 
- [x] Update Java SDK's README.md to refer to latest version. @artursouza 
- [x] Validate latest kubernetes install YAML for `dapr init --kubernetes` @yaron2 
- [ ] Announcement email and Twitter post @msfussell
