### ISSUE TITLE
Iteration Plan for August 2019

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#169]
This plan captures our work in **August**. This is a 4-week iteration. We will **ship** our August update in **early Sept**.

*Iteration Master:* @msfussell  

## Key Scenarios 
1) Private Preview SDK release to give to customers/CDAs/GBBs etc
2) Complete actor runtime capabilities including transaction and reminder/timer support
3) Design and goals specs for e2e and conformance tests
4) Improved diagnostics and distributed tracing
5) Doc structure
6) Kubernetes operational improvements

## Endgame
Aug 30th, 2019: Endgame begins
Sept 3rd, 2019: Endgame complete

## Plan Items
Below is a summary of the top-level plan items.

### Spec
- [x] https://github.com/actionscore/spec/issues/20 Actor Get Reminders API 💪
- [x] https://github.com/actionscore/spec/issues/14 Actor Granular State API
- [x] https://github.com/actionscore/spec/issues/13 API proposal: Actors State Batch API 

### Runtime
- [x] #130 Add granular state management for actors
- [x] #182  Pass headers for client calls to user service code
- [x] #17   Add reminder, timer capabilities for Actors
- [x] #89 Allow Actor runtime to fetch state instead of getting it on activation
- [x] #130 Add delete state API
- [x] #19 Add transactional support for state
- [x] #90 Add error codes to API return responses
- [x] #126 Distributed tracing 💪
- [x] #23 Use admission controller for k8s sidecar injection 💪
- [x] #114 Rename controller to operator
- [x] #258 Actors: Add Get API for Reminders
- [x] #260 Actors: Log reminders/timers errors in ActionsRT 💪
- [x] #247 Don't panic when app channel is not initialized 💪
- [x] #261 Actors: Use consistent url scheme for invoking reminders/timers in user code 💪

### CLI
- [x] #202 point actions init --kubernetes to helm rendered template
- [x] https://github.com/actionscore/cli/issues/30 Bring CLI output to product standard
- [x] https://github.com/actionscore/cli/issues/40 Add stop command 💪
- [x] https://github.com/actionscore/cli/issues/35 Fix port collision

### Preview Kit
- [x] #125 Define spec and automate the creation of Private Preview Actions Development Kit
- [x] #199 README.pdf for the Private Preview Actions Development Kit
- [x] #198 Define spec of Private Preview Actions Development Kit
- [x] #200 Validate Private Preview kit is customer and partner ready

### C# SDK
- [x] https://github.com/actionscore/cs-sdk/issues/2 Setup C# SDK CI build including Nupkg publish 
- [x] https://github.com/actionscore/cs-sdk/issues/7 Add Actor runtime components to sdk.
- [x] https://github.com/actionscore/cs-sdk/issues/5 Enable RPC like calls using ActorProxy.
- [x] https://github.com/actionscore/cs-sdk/issues/17 Enable non-RPC method calls using ActorProxy.
- [x] https://github.com/actionscore/cs-sdk/issues/26 Create docs and Readme
- [x] https://github.com/actionscore/cs-sdk/issues/31 Throw unwrapped exception instead of AggregatedException
- [x] https://github.com/actionscore/cs-sdk/issues/27 Change repo name from cs-sdk to dotnet-sdk
- [x] https://github.com/actionscore/cs-sdk/issues/25 Split nuget package into Actors and Actors.AspnetCore
- [x] https://github.com/actionscore/cs-sdk/issues/3 Automatically publish Nuget packages on CI build

### Demo/Sample
- [x] #189 Update/test samples to conform to API changes
- [x] #204 Create Pub/Sub Sample
- [x] #205 Add Architecture Diagrams to Samples
- [x] #265 Pub-Sub Subscriber logs don't show up

### Engineering Systems
- [x] #192 Move from Dep to Go Modules 
- [x] #81 Create Azure subscription for Actions 
- [x] #188 Enable anonymous access to ACR
- [x] #71 Review Docker tag policy
- [x] #267 e2e tests design and goals

Legend of annotations:

|Mark | Description|
|------|-----------|
| 🏃 | work in progress|
| ✋ | blocked task|
| 💪 | stretch goal for this iteration|
| 🔴 | missing issue reference|
| 🔵 | more investigation required to remove uncertainty|
| ⚫️ | under discussion within the team|
