### ISSUE TITLE
v0.9.0 Milestone Plan

### ISSUE THREAD

**Issue by orizohar** [dapr/dapr#1705]
*Milestone Lead:* @vinayada1 
*Milestone Buddy:*  @shalabhms 

## Key scenarios for this milestone 

* [x] [Address P1 bugs](https://github.com/dapr/dapr/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fbug+label%3Ap1)

* [x] [Support transactional state store for actors](https://github.com/dapr/components-contrib/issues/152)

* [x] [Developer experience improvments](https://github.com/dapr/cli/issues/343)

* [ ] [Continue perf and scale work](https://github.com/dapr/dapr/labels/area%2Ftest%2Fperformance)

* [ ] [Continue Long Hauls & E2E Tests](https://github.com/dapr/dapr/labels/area%2Ftest%2Fe2e)

* [x] [Continue Security](https://github.com/dapr/dapr/issues?q=is%3Aissue+label%3Akind%2Fsecurity+is%3Aopen)

### Release date - 16th July 2020

Legend of annotations:

|Mark | Description|
|------|-----------|
| 🏃 | work in progress|
| ✋ | blocked task|
| 💪 | stretch goal for this iteration|
| 🔴 | missing issue reference|
| 🔵 | more investigation required to remove uncertainty|
| ⚫️ | under discussion within the team|
