### ISSUE TITLE
Milestone 0.9.0 End Game

### ISSUE THREAD

**Issue by vinayada1** [dapr/dapr#1770]
## Schedule

End game Lead: @vinayada1 
End game buddy: @youngbupark 

This is the schedule for the 0.9.0 Release

07/13 05:00 PM PST code freeze for the release
07/16 Release date

- [x] Code freeze at 05:00 pm 07/13
- [x] No P0 issues before code freeze.
- [x] Create 0.2.0 relese branch for component-contrib @vinayada1 
- [x] Cut 0.2.0 releae for component-contrib @vinayada1 
- [x] update component-contrib pkg to 0.2.0 in dpar/dapr
- [x] Create 0.9.0 release branches for Dapr runtime @vinayada1   
- [x] Create 0.9.0 release branches for CLI @vinayada1
- [x] Cut the 0.9.0 rc release for Dapr runtime @vinayada1  
- [x] Cut the 0.9.0 rc release for CLI @vinayada1
- [x] Test and validate samples - @pruthvidhodda @vinayada1 @wcs1only @mukundansundar 
- [x] Test and validate the release - run through demos, review docs, E2E tests, manual testing, @yaron2 @Haishi2016 @amanbha @shalabhms @vinayada1 @LMWF @msfussell @pruthvidhodda 
- [x] Share 0.9.0-rc release with Azure Tools team to test VS Code and Remote Containers - Phil Hoff
- [x] Fix bugs
- [x] Test and validate the .NET SDK release v0.9.0-preview01 - run through samples, @LMWF
- [x] Test and validate the .Java SDK release v0.7.0-rc-1 - run through integration tests and samples, @artursouza 
- [x] Create 0.9.0-preview01 .NET SDK @amanbha @LMWF
- [x] Create 0.7.0-rc-1 Java SDK @artursouza @LMWF
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK . Checked them in release branch before cutting the release.@yaron2 
- [x] Verify breaking changes section in release notes @vinayada1  
- [x] Update Helm Charts in release branch before cutting the release @vinayada1 
- [x] Upload Nuget packages. - @LMWF @amanbha
- [x] Create 0.9.0 tag for docs in the repos. @vinayada1 
- [x] Create release-0.9.0 branch for samples, update version tag in the images, create v0.7.0 tag and update the readme in master @shalabhms @vinayada1 @pruthvidhodda
- [x] Upload new helm chart to ACR @yaron2 
- [x] Generate new Java docs based on the release version of the Java SDK and push to master. @artursouza 
- [x] Update Java SDK's README.md to refer to latest version. @artursouza 
- [x] Validate latest kubernetes install YAML for `dapr init --kubernetes` @yaron2 
- [x] Announcement email and Twitter post @orizohar
