### ISSUE TITLE
Milestone 0.10.0 End Game

### ISSUE THREAD

**Issue by pruthvidhodda** [dapr/dapr#1939]
End game Lead: @pruthvidhodda 
End game buddy: @mukundansundar 

This is the schedule for the 0.10.0 Release

08/18 1:00 PM PST code freeze for the release
08/20 Release date

- [x] Code freeze at 1:00 pm 08/18
- [x] No P0 issues before code freeze.
- [x] Create 0.3.0 release branch for component-contrib @pruthvidhodda  
- [x] Cut 0.3.0 release for component-contrib @pruthvidhodda  
- [x] update component-contrib pkg to 0.3.0 in dapr/dapr
- [x] Create 0.10.0 release branches for Dapr runtime @pruthvidhodda    
- [x] Create 0.10.0 release branches for CLI @pruthvidhodda 
- [x] Cut the 0.10.0 rc release for Dapr runtime @pruthvidhodda   
- [x] Cut the 0.10.0 rc release for CLI @pruthvidhodda 
- [x] Test and validate quickstarts - @pruthvidhodda @vinayada1  @wcs1only @mukundansundar @youngbupark
- [x] Test and validate the release - run through demos, review docs, E2E tests, manual testing, @yaron2 @Haishi2016 @amanbha @shalabhms @vinayada1 @LMWF @msfussell @pruthvidhodda 
- [x] Share and confirm tested 0.10.0-rc release with Azure Tools team to test Dapr VS Code extension and Remote Containers - Phil Hoff
- [x] Fix bugs
- [x] Update proto clients in cpp-sdk @wcs1only
- [x] Update proto clients in js-sdk @pruthvidhodda 
- [x] Update proto clients in rust-sdk @pruthvidhodda 
- [x] Test and validate the .NET SDK - run through samples, @LMWF, @vinayada1 
- [x] Test and validate the .Java SDK release v0.8.0-rc-1 - run through integration tests and samples, @wcs1only @mukundansundar 
- [x] Test and validate the python SDK release - run through samples, @youngbupark  ?
- [x] Test and validate the go SDK release  - run through samples, @mchmarny 
- [x] Create release-0.10.0 .NET SDK branch @vinayada1  @LMWF
- [x] Create 0.8.0-rc-1 Java SDK @mukundansundar  @wcs1only 
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK . Checked them in release branch before cutting the release.@yaron2 
- [x] Verify breaking changes section in release notes @pruthvidhodda   
- [x] Update Helm Charts in release branch before cutting the release @pruthvidhodda @yaron2 ? 
- [x] Release dapr/dapr and dapr/cli
- [x] Create python SDK and docs @youngbupark 
- [x] Create go SDK and docs @mchmarny  
- [x] Upload Nuget packages. - @LMWF @vinayada1 
- [x] Create 0.10.0 tag for docs in the repos. @pruthvidhodda  
- [x] Create release-0.10.0 branch for quickstarts, update version tag in the images, create v0.10.0 tag and update the readme in master @shalabhms @vinayada1 @pruthvidhodda
- [x] Upload new helm chart to ACR @yaron2 
- [x] Release 0.8.0 version of java-sdk
- [x] Generate new Java docs based on the release version of the Java SDK and push to master. @mukundansundar @wcs1only  
- [x] Update Java SDK's README.md to refer to latest version. @mukundansundar @wcs1only  
- [x] Announcement email and Twitter post @orizohar

**Comment by tomkerkhove** [comment]
v0.10.0 RC0 is out: https://github.com/dapr/dapr/releases/tag/v0.10.0-rc.0

Any overview of what's included?

**Comment by yaron2** [comment]
> v0.10.0 RC0 is out: https://github.com/dapr/dapr/releases/tag/v0.10.0-rc.0
> 
> Any overview of what's included?

Release notes will be added soon
