### ISSUE TITLE
Milestone 0.11.0 End Game

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#2084]
End game Lead: @mukundansundar 
End game buddy: @youngbupark 

This is the schedule for the 0.11.0 Release

09/24 4:30 PM PST code freeze for the release
09/30 Release date

- [x] Code freeze at 4:30 pm 09/24
- [x] No P0 issues before code freeze.
- [x] Create 0.4 release branch for component-contrib @youngbupark 
- [x] Cut 0.4.1 release for component-contrib @youngbupark 
- [x] update component-contrib pkg to 0.4.1 in dapr/dapr @youngbupark @mchmarny 
- [x] Create 0.11.0 release branches for Dapr runtime @mukundansundar  
- [x] Create 0.11.0 release branches for CLI @mukundansundar 
- [x] Cut the 0.11.0 rc release for Dapr runtime @mukundansundar    
- [x] Cut the 0.11.0 rc release for CLI @mukundansundar  
- [x] Cut the 0.9.0 rc release for Java SDK @artursouza  
- [x] Test and validate latest dashboard RC. @artursouza  
- [x] Test [Certificate export and Kubernetes upgrade path](https://github.com/dapr/docs/tree/master/howto/deploy-k8s-prod#updating-the-control-plane-pods). @yaron2 
- [x] Test and validate quickstarts - @mukundansundar @vinayada1  @wcs1only @youngbupark @tcnghia @halspang 

- [x] Test and validate quickstarts in Linux- @mukundansundar @vinayada1  @wcs1only @youngbupark @tcnghia @halspang @msfussell 
- [x] Test and validate quickstarts in ARM64- @mukundansundar @vinayada1  @wcs1only @youngbupark @tcnghia @halspang @msfussell 
- [x] Test and validate quickstarts in Windows- @mukundansundar @vinayada1  @wcs1only @youngbupark @tcnghia @halspang @msfussell 
- [x] Test and validate the release - run through demos, review docs, E2E tests, manual testing, @yaron2 @vinayada1 @msfussell @youngbupark 
- [x] Test and release azure-function-extensions @vinayada1 (No release needed this time for 0.11.0)
- [x] Test and release dapr-workflows @yaron2
- [x] Share and confirm tested 0.11.0-rc release with Azure Tools team to test Dapr VS Code extension and Remote Containers - Phil Hoff
- [x] Fix bugs
- [x] Update proto clients in cpp-sdk @wcs1only
- [x] Update proto clients in js-sdk @youngbupark 
- [x] Update proto clients in rust-sdk @youngbupark 
- [x] Test and validate the .NET SDK - run through samples, @vinayada1 
- [x] Test and validate the .Java SDK release v0.9.0-rc-1 - run through integration tests and samples @artursouza 
- [x] Test and validate the python SDK release - run through samples, @youngbupark 
- [x] Test and validate the go SDK release  - run through samples, @mchmarny 
- [x] Create release-0.11.0 .NET SDK branch @vinayada1 
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the release. @mukundansundar @youngbupark 
- [x] Verify breaking changes section in release notes @mukundansundar @msfussell 
- [x] Release dapr dashboard @artursouza 
- [x] Update dashboard version in Helm Charts @artursouza 
- [x] Update Helm Charts in release branch before cutting the release @mukundansundar  @youngbupark @vinayada1 https://github.com/dapr/dapr/pull/2161
- [x] Update Docker image tags in release branch before cutting the release @mukundansundar  @youngbupark @vinayada1
- [x] Release dapr/dapr and dapr/cli @mukundansundar 
- [x] Release cpp-sdk @wcs1only  
- [x] Release js-sdk @youngbupark 
- [x] Release rust-sdk @youngbupark 
- [x] Create python SDK and docs @youngbupark 
- [x] Create go SDK and docs @mchmarny  
- [x] Release dotnet SDK and release nuget packages - @vinayada1 
- [x] Create 0.11.0 tag for docs in the repos. @mukundansundar @youngbupark 
- [x] Create release-0.11.0 branch for quickstarts, update version tag in the images, create v0.11.0 tag and update the readme in master @wcs1only @mukundansundar @youngbupark 
- [x] Upload new helm chart to ACR @youngbupark 
- [x] Release 0.9.0 version of java-sdk @artursouza
- [x] Generate new Java docs based on the release version of the Java SDK and push to master.@artursouza 
- [x] Update Java SDK's README.md to refer to latest version. @artursouza 
- [x] Announcement email and Twitter post and **blog** @orizohar  
- [x] Merge back release-0.11.0 branch into master for required repos. @mukundansundar @youngbupark

**Comment by mukundansundar** [comment]
Dapr upgrade guidelines. https://github.com/dapr/docs/tree/master/howto/deploy-k8s-prod#upgrading-dapr-with-helm 

Here the helm chart needs to point to the RC for testing RC

**Comment by mukundansundar** [comment]
https://github.com/dapr/dapr/pull/2119

**Comment by mukundansundar** [comment]
Merge back changes PRs 

https://github.com/dapr/dapr/pull/2165

https://github.com/dapr/cli/pull/476
