### ISSUE TITLE
Move Trace exporters to Dapr core and add OpenTelemetry support

### ISSUE THREAD

**Issue by tcnghia** [dapr/dapr#2337]
## In what area(s)?

/area runtime
/area docs
/area test-and-release

## Proposal

In https://github.com/dapr/dapr/issues/1080 we updated documentation using Local Forwarder to OpenTelemetry Collector. That opens the possibility to rely solely on OpenTelemetry Collector for our trace extensions and avoid maintaining an extension point for the exporter components since OpenTelemetry Collector already supports all trace backends that we currently support and several more.

Before OpenTelemetry is GA, however, we will keep supporting Zipkin protocol as it is well understood by many tracing backends. This will help ensure existing tracing setups documented in our samples continue to work without big changes. In addition to that, we will keep supporting Zipkin for some time even after OpenTelemetry is GA to allow time for backends to add direct support for OpenTelemetry GA and also time for our users to migrate.

Since supporting both Zipkin and OpenTelemetry we already have enough coverage, we will deprecate the exporter components and will move Zipkin & OpenTelemetry tracing support into Dapr core.

### Before OpenTelemetry GA
- [x] Extend our Configuration CRD to support the new field `tracing.zipkin.endpointAddress` (https://github.com/dapr/dapr/issues/2521)

```diff
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    samplingRate: "1"
+   # new section to include Zipkin configurations. Currently we only need endpoint
+   # but going forward we may consider things like API key as well.
+   zipkin:
+     endpointAddress: "https://zipkin.default.svc.cluster.local:9411/api/v2/spans"
```
- [x] Move the Zipkin trace exporter into dapr/dapr, consuming the new field `tracing.zipkin.endpointAddress` (https://github.com/dapr/dapr/issues/2522)
- [x] Update Tracing section of Configuration (https://github.com/dapr/docs/issues/978)
- [x] Update CLI to move [default Zipkin component](https://github.com/dapr/cli/blob/8f02a68a700ded58f71c6c48183e4d3ce837aa42/pkg/standalone/standalone.go#L888) into [default Configuration](https://github.com/dapr/cli/blob/8f02a68a700ded58f71c6c48183e4d3ce837aa42/pkg/standalone/standalone.go#L870) (https://github.com/dapr/cli/issues/534)
- [x] Update Dapr diagnosis with tracing how-tos (https://github.com/dapr/docs/issues/967)
- [x] Update Dapr Observability Quickstart (https://github.com/dapr/quickstarts/issues/336)

- [x] Advertise/announce the deprecation of the trace exporter extension point, as well as new documents (https://github.com/dapr/docs/issues/967, https://github.com/dapr/java-sdk/issues/404)

- [ ] Add an end to end tests that validate trace receipt (possibly through the logging exporter of OpenTelemetry collector)

### After OpenTelemetry GA (**blocked**)

- [ ] Extend our Configuration CRD to support the new field `tracing.opentelemetry.endpointAddress`. Add tracing implementation for OpenTelemetry.

```diff
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    samplingRate: "1"
+   # new section to include OpenTelemetry configurations
+   opentelemetry:
+     endpointAddress: "..."
```

- [ ] Add samples to use OpenTelemetry protocol

**Comment by tcnghia** [comment]
cc @yaron2 @msfussell @youngbupark can you please help review?  Thanks

**Comment by msfussell** [comment]
Very clear write up. 

Re the "However, moving to OpenTelemetry Collector will require the installation of the OpenTelemetry Collector process (in self-hosted mode), or Pods (on Kubernetes). On Kubernetes, this moves the default installation from 5 Pods (dashboard, operator, placement, sentry, sidecar-injector) to 6 Pods. The gain in functionalities may justify this foot-print increase" - **I agree with this decision. Operational telemetry and diagnostics are essential for any K8s deployment.**

Feedback 
1) Can you include a Prometheus example also for metrics? (Example should be a separate configuration)
2) Q: Should we enable more than one collector? e.g. Prometheus and OpenTelemetry? I see no reason to prevent this, although unusual. 
3) The default for v.10 RC1 release will remain Prometheus for metrics. Later in v1.0 RC2 release we can change this.
4) Need to test to ensure that OT collector works with ZipKin and AppInsight
5) I think you missed that by default in the slef-hosted experience we would also install the OpenTelemetry collector for ZipKin to maintain parity. Or at leas make this clear in point 2 above on installation (both K8s and self-hosted)

**Comment by tcnghia** [comment]
> Very clear write up.
> 
> Re the "However, moving to OpenTelemetry Collector will require the installation of the OpenTelemetry Collector process (in self-hosted mode), or Pods (on Kubernetes). On Kubernetes, this moves the default installation from 5 Pods (dashboard, operator, placement, sentry, sidecar-injector) to 6 Pods. The gain in functionalities may justify this foot-print increase" - **I agree with this decision. Operational telemetry and diagnostics are essential for any K8s deployment.**
> 

Thanks!

> Feedback
> 
> 1. Can you include a Prometheus example also for metrics? (Example should be a separate configuration)

My understanding is that since Prometheus is a scraper, we don't need any Prometheus configuration on our side. Dapr sidecar exposes a port that speaks Prometheus and that's it (cc @yaron2 @youngbupark)

> 2. Q: Should we enable more than one collector? e.g. Prometheus and OpenTelemetry? I see no reason to prevent this, although unusual.

I think since they are sort of different model (Prometheus: pull, OpenTelemetry: push), so it may be a bit less unusual to have them both? (cc @youngbupark)

> 3. The default for v.10 RC1 release will remain Prometheus for metrics. Later in v1.0 RC2 release we can change this.

Since `daprd` will serve Prometheus metrics always when metrics is enabled, I think this point means that _we will update docs to use OpenTelemetry for metrics post-RC1_. This sounds good to me. Thanks for pointing out.

> 4. Need to test to ensure that OT collector works with ZipKin and AppInsight

Updated. Thanks for pointing out.

> 5. I think you missed that by default in the slef-hosted experience we would also install the OpenTelemetry collector for ZipKin to maintain parity. Or at leas make this clear in point 2 above on installation (both K8s and self-hosted)

Updated. Thanks

**Comment by tcnghia** [comment]
@msfussell I've put the work items into **v1.0-rc1** and **v1.0-rc2** parts. Since we have about 3 days left before code freeze for **v1.0-rc1** I didn't put a whole lot of items in there. Let me know if this split looks good to you.

**Comment by youngbupark** [comment]
> > Feedback
> > 
> > 1. Can you include a Prometheus example also for metrics? (Example should be a separate configuration)
> 
> My understanding is that since Prometheus is a scraper, we don't need any Prometheus configuration on our side. Dapr sidecar exposes a port that speaks Prometheus and that's it (cc @yaron2 @youngbupark)

The configuration for prometheus can be set by command flags now e.g. `-metrics-port`. I would keep these configuration as is. Prometheus is de facto metric backend. Most of CNCF projects use prometheus by default. If metric.enabled is true without opentelemetry, then prometheus will be an exporter for metric. it will not break the existing scenario. 

> 
> > 1. Q: Should we enable more than one collector? e.g. Prometheus and OpenTelemetry? I see no reason to prevent this, although unusual.
> 
> I think since they are sort of different model (Prometheus: pull, OpenTelemetry: push), so it may be a bit less unusual to have them both? (cc @youngbupark)

To be clear, Prometheus is not a collector, but also metric backend. it has its own storage to aggregate and store metrics. Opentelemetry collector is just a collector.

So the answer is that it's up to user's infra. If user's existing infra uses prometheus for metrics, they still need prometheus even if they use opentelemetry collector.

> 
> > 1. The default for v.10 RC1 release will remain Prometheus for metrics. Later in v1.0 RC2 release we can change this.
> 
> Since `daprd` will serve Prometheus metrics always when metrics is enabled, I think this point means that _we will update docs to use OpenTelemetry for metrics post-RC1_. This sounds good to me. Thanks for pointing out.

For this, we need to listen to customer feedback before deprecating prometheus exporter for metric.

**Comment by youngbupark** [comment]
@tcnghia I think we need to think about how to handle control plane services' metrics.

**Comment by RadoslavGatev** [comment]
The current implementation of the Azure Monitor exporter that talks to App Insights seems to support traces only.

**Comment by youngbupark** [comment]
> The current implementation of the Azure Monitor exporter that talks to App Insights seems to support traces only.

This is true. We leverage [otel collector exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/azuremonitorexporter) to emit trace to app insights. this exporter supports only trace.

**Comment by tcnghia** [comment]
I've updated the plan with new proposal. TL;DR: we want to keep Zipkin support as the main tracing format before we completely switch to OpenTelemetry. This ensures that most users are not affected, and also reduce the number of work items.

**Comment by msfussell** [comment]
@tcnghia - Is this now complete and can this be closed?

**Comment by tcnghia** [comment]
@msfussell we still need an E2E test (before 1.0) and the  OpenTelemetry migration (after 1.0)

**Comment by tcnghia** [comment]
Since OpenTelemetry is not yet GA, we will push the move to OpenTelemetry post v1.0. I've updated the issue name to match.

cc @msfussell @yaron2
