### ISSUE TITLE
Make service invocation great again

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#2342]
## In what area(s)?

/area runtime

## Background

Daprized application can communicates with the other applications. Application exposes HTTP/1.1 and gRPC endpoints and calls HTTP/1.1 and gRPC service invocation API to interact with Dapr sidecar. Dapr service invocation exchanges data between caller and callee regardless of which protocol applications use.

1. Caller ---`HTTP`--> Dapr Sidecar --`Internal gRPC`--> Dapr Sidecar --`HTTP`--> Callee
2. Caller ---`gRPC`--> Dapr Sidecar --`Internal gRPC`--> Dapr Sidecar --`gRPC`--> Callee
3. [cross-protocol] Caller ---`gRPC`--> Dapr Sidecar --`Internal gRPC`--> Dapr Sidecar --`HTTP`--> Callee
4. [cross-protocol] Caller ---`HTTP`--> Dapr Sidecar --`Internal gRPC`--> Dapr Sidecar --`gRPC`--> Callee

For non cross-protocol invocation (1, 2), Dapr bypasses the same protocol request and response from callee to caller like a reverse proxy. For cross-protocol invocation (3, 4), Dapr converts the request and response for caller's protocol.

## Problem

For cross-protocol scenarios, the current implementation can lose callee's response body. This proposal reviews the current behavior and propose new behavior to not lose the original response from callee application.

### gRPC to HTTP/1.1

Dapr truncates HTTP error response body to fit gRPC [ErrorInfo](https://cloud.google.com/apis/design/errors#errorinfo) [rich error model protobuf message](https://grpc.io/docs/guides/error/) when converting HTTP error response to gRPC error response in grpc-to-http scenario. Even if Dapr doesn't truncate the http body, the large payload from HTTP callee application will be truncated by HTTP/2 protocol layer because [rich error model protobuf message is stored in HTTP trailer stream](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses) whose max size is smaller than 8 KiB (depends on gRPC implementation).

### HTTP/1.1 to gRPC

If gPRC application returns rich error model status, dapr doesn't populate this error details to HTTP response body.

## Current behaviors for cross-protocol invocation

The response status code represents callee application status code by mapping the status code between HTTP/1.1 and gRPC protocol. 

### gRPC to HTTP

1. Headers: see [the original proposal](https://github.com/dapr/dapr/issues/1409).
2. Response status code
   * Populate `dapr-http-status` to gRPC response header
   * Convert HTTP successful status code (200 - 299) to GRPC response status code (OK)
   * Convert HTTP failure status code (>= 300) to gRPC status code by the [mapping](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/pkg/messaging/v1/util.go#L278-L311)
3. HTTP Response body conversion
   * HTTP successful status code (200 - 299)
     - convert content-type header and response body to [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80)
   * HTTP failure status code(>= 300)
     - create ErrorInfo gRPC status detail and populate HTTP statuscode to `http.code` metadata and HTTP body to `http.error_message` metadata in ErrorInfo, respectively.
     - truncate `http.error_message` error response body value to 64 characters.

### HTTP to gRPC

1. Headers: see [the original proposal](https://github.com/dapr/dapr/issues/1409).
2. Status code
   * Convert gRPC `OK` status  to HTTP status code (200)
   * Convert gRPC `non-OK` status to the corresponding HTTP status code by the [mapping](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/pkg/messaging/v1/util.go#L233-L276)
3. gRPC response body conversion
   * gRPC `OK` status code
     - Convert [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80) protobuf message to HTTP Response body with content_type header
     - Reject conversion for custom protobuf message.
   * gRPC `non-OK` status codes
     - No conversion for Rich error [Status](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) protobuf message

## New proposal

New behavior will not convert status code between HTTP/1.1 and gRPC. Instead, the status code will represent the status of *caller's request delivery* and populate the callee's original response status code to the header. 

### gRPC to HTTP

1. Headers: No change
2. Response status code
   * Return GRPC response status code (`OK`) unless there is transport layer error or internal gRPC communication error
     > Note: Transport layer error must be converted to gRPC error code.
   * Populate `dapr-http-status-code` to gRPC response header.
3. HTTP Response body conversion
   * Populate content-type header and response body to [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80)

### HTTP to gRPC

1. Headers: No change
2. Response status code
   * Return HTTP 200 code unless there is transport layer error or internal gRPC communication error
     > Note: Transport layer error must be converted to HTTP error code.
   * Populate the original grpc status code to `dapr-grpc-status-code` HTTP/1.1 header
3. gRPC Response body conversion
   * gRPC callee returns `OK` status
     * user app returns Dapr [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80) protobuf message.
       * content_type in [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80) to HTTP contentType header
       * data in [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80) to HTTP response body
     * user app returns custom protobuf message
       * Populate `application/x-protobuf` to HTTP ContentType header
       * Populate the serialized protobuf message (bytes array) to HTTP response body
   * gRPC callee returns `non-OK` status
     * Populate `application/json` to HTTP ContentType Header
     * Using [jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb), Json-serialize gRPC rich error model [Status](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) protobuf message to HTTP response body.

example

```json
{
   "code": 14,
   "message": "Unavailable",
   "details": [{
      "@type": "type.googleapis.com/google.rpc.RetryInfo",
      ...
    }]
}
```

### User experience change

New proposal will resolve the problem to lose the callee's response data. However, the response status code represents *the status of invocation request delivery* from caller to callee in cross-protocol communication scenarios.

SDK and user application which use HTTP or gRPC API directly need to change these error-handling logic. These must check `dapr-http-status-code` or `dapr-grpc-status-code` header to know the original callee's status code if status code is successful code.

A user who uses gRPC service invocation api will no longer get exception except for transport or internal gRPC error (such as permission denied by accesslist). For example, SDK must check the status code header and then return error object or throw except accordingly.

### Observability middleware change

metric and trace middlewares must use `dapr-http-status-code` or `dapr-grpc-status-code` response header to decide whether request is succeeded or not.

## Related issue

#2220 
https://github.com/dapr/dotnet-sdk/issues/399

## Work items

- [ ] Remove conversion layer in daprd and populate grpc error detail to http error response
- [ ] Fix e2e test
- [ ] [dotnet-sdk] Use new error-handling
- [ ] [java-sdk] Use new error-handling
- [ ] [go-sdk] Use new error-handling
- [ ] [python-sdk] Use new error-handling

## Open questions

1. Inconsistency between cross-protocol and non-cross-protocol invocations

## Release Note

RELEASE NOTE: **Change** response handling for cross-protocol invocation.

**Comment by yaron2** [comment]
+1, I support this design proposal.

Just to be clear, this will not affect users who use service invocation for HTTP to HTTP and gRPC to gRPC, correct?

**Comment by youngbupark** [comment]
> +1, I support this design proposal.
> 
> Just to be clear, this will not affect users who use service invocation for HTTP to HTTP and gRPC to gRPC, correct?

No, no impact/change for non-cross protocol scnearios.

**Comment by artursouza** [comment]
LGTM

**Comment by artursouza** [comment]
No need to call out breaking change in the RELEASE NOTE, the script understands the "braking-change" label.

**Comment by mchmarny** [comment]
In general, this makes sense. The bit I'm somewhat concerned about is the potential for "silent errors" resulting from the use-case number 3, existing gRPC callers targeting app over HTTP.

> a user who uses gRPC service invocation api will no longer get exception except for transport or internal gRPC error (such as permission denied by accesslist)

If I understand this correctly, in cases when the callee side has been updated to include the proposed implementation, all calling apps invocations on the gRPC API against user code over on HTTP would succeed... **even if there were errors**; as these apps don't know anything about the new error "hint" inthe header, right? 

I suspect more Dapr user apps expose HTTP than gRPC protocol. We also have significant SD usage, which for most part default to gRPC. The potential for "everything works as expected" while silently erring could be impacting a significant percentage of existing apps. 

While I don't see this as a blocker to implementation, we are going to have to be explicit about this scenarios with users... probably more than a line-item in the release notes IMO.

**Comment by youngbupark** [comment]
> In general, this makes sense. The bit I'm somewhat concerned about is the potential for "silent errors" resulting from the use-case number 3, existing gRPC callers targeting app over HTTP.
> 
> > a user who uses gRPC service invocation api will no longer get exception except for transport or internal gRPC error (such as permission denied by accesslist)
> 
> If I understand this correctly, in cases when the callee side has been updated to include the proposed implementation, all existing calling apps invocations on the gRPC API against user code over on HTTP would succeed...

Caller using gRPC API always gets gRPC Status `OK` unless there is transport related errors. 

> **even if there were errors**; as these apps don't know anything about the new error "hint" in the header, right?

maybe you want to say `in the status code` instead of `in the header`. **Even if callee returns error (HTTP error code)**, caller must look at `dapr-http-status-code` header to decide whether caller returns error or not.

> I suspect more Dapr user apps expose HTTP than gRPC protocol. We also have significant SDK usage, which for most part default to gRPC. The potential for "everything works as expected" while silently erring could be impacting a significant percentage of existing apps.
> 

Therefore the convenient layer in SDK must see header and return the error object or throw error for the user. 

> While I don't see this as a blocker to implementation, we are going to have to be explicit about this scenarios with users... probably more than a line-item in the release notes IMO.

Yes. I agree 100% on this.

**Comment by rynowak** [comment]
Chiming in to say that the current experience is broken for a lot of different use cases for .NET.

When the application is using HTTP and returns a non-200 response there's typically some content to go along with it, and using metadata to flow that limits its size. The .NET SDK currently uses gRPC for invoke, which results in this truncation occurring for .NET services called via invoke through the Dapr SDK.

As an example. ASP.NET Core MVC will use the rfc-7807 format for returning business validation errors (like omitting a required field). When this happens it results in a truncated (and thus not valid JSON) response. Example client code [here](https://github.com/rynowak/dapr-httpclient-extravaganza/blob/main/samples/BankClient/DaprClientExample.cs#L65).

This problem is really bad for .NET users, and we need to either make sure sure the runtime propagates the entire content, or push users down a different path that doesn't involve gRPC->HTTP invokes.

**Comment by artursouza** [comment]
@rynowak Do you think the proposal here will be helpful to solve that? See "Populate content-type header and response body to common.InvokeResponse" in the description. This issue seems to be a priority (P1) for v1.0.0, not?

**Comment by rynowak** [comment]
> This issue seems to be a priority (P1) for v1.0.0, not?

This either must be addressed or we need to stop using gRPC for invocation in requests. Any HTTP service that uses the response body for error info (super common) will likely see their responses truncated.

**Comment by artursouza** [comment]
> > This issue seems to be a priority (P1) for v1.0.0, not?
> 
> This either must be addressed or we need to stop using gRPC for invocation in requests. Any HTTP service that uses the response body for error info (super common) will likely see their responses truncated.
> 
> You can see my full thoughts on this in longer form here: [dapr/dotnet-sdk#526](https://github.com/dapr/dotnet-sdk/issues/526) I'm questioning at this point if _anyone_ benefits from the HTTP over gRPC style of invoke, vs just using HTTP. I'm planning to make it easier with the .NET SDK to use the built-in .NET `HttpClient` APIs - I expect a lot of users will say that it simplifies things for them.

I had a conversation with @yaron2  and he explained your point to me. I can see why using HTTP for the invoke feature makes sense. For scenarios where grpc to grpc is preferred due to performance, we can make it a configuration in the SDK. The Java SDK, for example, has some flags that can be set via environment variables.

**Comment by msfussell** [comment]
This affects each of the SDKs. Separate bugs are needed to track each SDK work.

**Comment by yaron2** [comment]
@youngbupark assigned to you, FYI. As mentioned, we only need to work on the HTTP to gRPC changes.

**Comment by youngbupark** [comment]
If we want to support http to grpc scenario, then I recommend to keep the current behavior of status code conversion. This makes a lot easier to handle distributed trace and metrics. Otherwise, dapr middleware for trace and metrics always needs to look at `dapr-grpc-status-code` header and even user application reads `dapr-grpc-status-code` header to get the success status from the span, which is not the standard.

### HTTP to gRPC

1. Headers: No change
2. Response status code
   * ~Return HTTP 200 code unless there is transport layer error or internal gRPC communication error~
     ~> Note: Transport layer error must be converted to HTTP error code.~
   * ~Populate the original grpc status code to `dapr-grpc-status-code` HTTP/1.1 header~
3. gRPC Response body conversion
   * gRPC callee returns `OK` status
     * user app returns Dapr [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80) protobuf message.
       * content_type in [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80) to HTTP contentType header
       * data in [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80) to HTTP response body
     * user app returns custom protobuf message
       * Populate `application/x-protobuf` to HTTP ContentType header
       * Populate the serialized protobuf message (bytes array) to HTTP response body
   * gRPC callee returns `non-OK` status
     * Populate `application/json` to HTTP ContentType Header
     * Using [jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb), Json-serialize gRPC rich error model [Status](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) protobuf message to HTTP response body.

example

```json
{
   "code": 14,
   "message": "Unavailable",
   "details": [{
      "@type": "type.googleapis.com/google.rpc.RetryInfo",
      ...
    }]
}
```

**Comment by yaron2** [comment]
> If we want to support http to grpc scenario, then I recommend to keep the current behavior of status code conversion. This makes a lot easier to handle distributed trace and metrics. Otherwise, dapr middleware for trace and metrics always needs to look at `dapr-grpc-status-code` header and even user application need to read `dapr-grpc-status-code` header to get the success status from the span, which is not the standard.
> 
> ### HTTP to gRPC
> 1. Headers: No change
> 2. Response status code
>    
>    * ~Return HTTP 200 code unless there is transport layer error or internal gRPC communication error~
>      ~> Note: Transport layer error must be converted to HTTP error code.~
>    * ~Populate the original grpc status code to `dapr-grpc-status-code` HTTP/1.1 header~
> 3. gRPC Response body conversion
>    
>    * gRPC callee returns `OK` status
>      
>      * user app returns Dapr [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80) protobuf message.
>        
>        * content_type in [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80) to HTTP contentType header
>        * data in [common.InvokeResponse](https://github.com/dapr/dapr/blob/1c21def42063c0f3a58ca19b69dcd46874ad3611/dapr/proto/common/v1/common.proto#L70-L80) to HTTP response body
>      * user app returns custom protobuf message
>        
>        * Populate `application/x-protobuf` to HTTP ContentType header
>        * Populate the serialized protobuf message (bytes array) to HTTP response body
>    * gRPC callee returns `non-OK` status
>      
>      * Populate `application/json` to HTTP ContentType Header
>      * Using [jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb), Json-serialize gRPC rich error model [Status](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) protobuf message to HTTP response body.
> 
> example
> 
> ```json
> {
>    "code": 14,
>    "message": "Unavailable",
>    "details": [{
>       "@type": "type.googleapis.com/google.rpc.RetryInfo",
>       ...
>     }]
> }
> ```

@artursouza @rynowak I want your opinion here regarding the status header.

@youngbupark my concerns is this: When calling Dapr over HTTP to invoke a gRPC service, how can a user distinguish between a gRPC error returned by the Dapr runtime and an application level error returned by the callee, both using the same error code?

**Comment by youngbupark** [comment]
> @youngbupark my concerns is this: When calling Dapr over HTTP to invoke a gRPC service, how can a user distinguish between a gRPC error returned by the Dapr runtime and an application level error returned by the callee, both using the same error code?

IF we want to distinguish callee's protocol explicitly, we can populate `dapr-grpc-status-code`, but I recommend to convert the callee's gRPC status to HTTP status code for the compatibility of opentelemetry library. User can still get the original gRPC response code from the http response header.

**Comment by youngbupark** [comment]
> @youngbupark my concerns is this: When calling Dapr over HTTP to invoke a gRPC service, how can a user distinguish between a gRPC error returned by the Dapr runtime and an application level error returned by the callee, both using the same error code?

Even for HTTP->HTTP and GRPC->GRPC, user is hard to distinguish Dapr runtime error and application level error until he or she looks at the response body. This will apply the same to http->gRPC protocol. Regardless of the status code conversion, SDK or user will need to look at the response body. So SDKs or users can use the same logic to http->gRPC protocol.

However, if we want users or SDKs to distinguish callee's protocol explicitly, we can populate `dapr-grpc-status-code`, but I recommend to convert the callee's gRPC status to HTTP status code for the compatibility of opentelemetry library. User can still get the original gRPC response code from the http response header.

**Comment by rynowak** [comment]
If I understand the proposal here right...

As an HTTP caller, I can make a request and not care what the implementation of the service used, because the HTTP status code tells me the status.

Ex: If the callee service uses gRPC and reported status Internal, I get a 500. If the callee service reported InvalidArgument, I get a 400.

If this is experience we should aspire to - the fact that Dapr can translate HTTP->gRPC becomes an implementation detail. The only thing we're missing here compared to gRPC gateway is the JSON<->Protobuf conversion (but I digress).

As far as propagating the original gRPC status for users, what does gRPC gateway do? It's ideal if we can leverage an de-facto existing standard where possible.

For HTTP - the protocol specifies that there might be any number of proxies/caches in between you and the callee. The protocol doesn't specify any means get getting every status code from every link in the chain, and in practice this is not a problem.

If we need a means of telling the difference between an error coming from Dapr and from a downstream callee, the right thing to do would probably be based on introducing a content type like `application/daprerror+json`. This allows the caller to know what kind of content is in the response without trying to parse it. This might be more complex than what we really want to do, but IMO it's the "right thing".

> If we want to support http to grpc scenario, then I recommend to keep the current behavior of status code conversion. This makes a lot easier to handle distributed trace and metrics.

Not meant as a callout, but the user experience and simplicity of writing code that uses Dapr is the thing we need to optimize for. If the tracing part is a blocker, then lets drill into it. If it means we have to write some additional code in the runtime then that's the right tradeoff.

**Comment by youngbupark** [comment]
> As far as propagating the original gRPC status for users, what does gRPC gateway do? It's ideal if we can leverage an de-facto existing standard where possible.
> 

We leveraged gRPC gateway to dapr for http->grpc invocation initially. Regarding the conversion from gRPC to http status code, please see this - https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/errors.go#L15

**Comment by yaron2** [comment]
Closes by https://github.com/dapr/dapr/pull/2683.

Thanks @youngbupark!
