### ISSUE TITLE
v1.0 Milestone 2 Plan

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#2345]
*Milestone Lead:* @wcs1only
*Milestone Buddy:*  @artursouza 

## Deliverables for this milestone 

* [ ] Release v1.0-rcX
* [ ] Addressed customer feedback from previous RC
* [ ] Review of SDKs complete 
* [ ] Review CLI complete
* [ ] Long Running tests measured daily
* [ ] Performance and scalability tests numbers measured and published 
* [ ] P1 bugs
* [ ] GTM plan activities complete

**Starts - 18th Nov 2020** 
**Endgame starts - 11th Dec 2020** 
**Release date - 17th Dec 2020** 

RELEASE NOTE: N/A

**Comment by wcs1only** [comment]
Released on Dec 18th!
