### ISSUE TITLE
v1.0 Milestone 3 Plan

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#2346]
*Milestone Lead:* 
*Milestone Buddy:*  

## Deliverables for this milestone 

* [ ] Release v1.0-rc3
* [ ] Component certification complete and GA components signed-off
* [ ] Versioning testing sign-off
* [ ]  E2E Scenario Testing complete
* [ ] Release processes automated
* [ ] CELA Sign off
* [ ] Support guidance complete
* [ ] All known breaking changes complete
* [ ]  Samples and Quickstarts complete
* [ ] Getting started usability review complete
* [ ] GTM plan activities complete

**Starts - 21st Dec 2020** 
**Endgame starts - 22nd Jan 2021** 
**Release date - 28th Jan 2021**
