### ISSUE TITLE
v1.0 Milestone 4 Plan

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#2347]
*Milestone Lead:* 
*Milestone Buddy:*  

## Deliverables for this milestone 

* [ ] Release v1.0-rc4 
* [ ] Addressed customer feedback from previous RC
* [ ] Documentation complete
* [ ] Samples and quickstarts complete
* [ ] "Getting Started" usability review complete
* [ ] GTM plan activities complete

**Starts - 9th Jan 2021** 
**Endgame starts - 25th Jan 2021** 
**Release date - 28th Jan 2021**

**Comment by yaron2** [comment]
Dupe of endgame
