### ISSUE TITLE
v1.0 Milestone 1 Plan

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#2350]
*Milestone Lead:* @artursouza 
*Milestone Buddy:*  @youngbupark 

## Deliverables for this milestone 

* [ ] Release v1.0-rc1
* [ ] Functional feature complete 
* [ ] Customers start using the RC release to provide feedback
     * [ ] Zeiss given early v1.0-rc1 release
     * [ ] Bosch given early v1.0-rc1 release
     * [ ] Ignition Group early given v1.0-rc1 release
* [ ] GTM plan activities  complete

**Starts - 1st Oct 2020** 
**Endgame starts - 10th Nov  2020** 
**Release date - 13th Nov 2020** 

RELEASE NOTE: NOT APPLICABLE
