### ISSUE TITLE
v1.0.0 Milestone 1 End Game

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#2394]
End game Lead: @artursouza 
End game buddy: @wcs1only 

This is the schedule for the v1.0.0 Milestone 1 release

11/9 11:59 PM PST code freeze for the release
11/10 Preview build date

- [x] Code freeze at 11:59 pm 11/9
- [x] No P0 issues before code freeze.
- [x] E2E and perf tests are passing.
- [x] Create release-1.0 branch for component-contrib
- [x] Cut 1.0.0-rc1 release for component-contrib
- [x] Update component-contrib pkg to 1.0.0-rc1 in dapr/dapr master branch
- [x] Create release-1.0 branches for Dapr runtime
- [x] Create release-1.0 release branches for CLI
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release.
- [x] Cut the 1.0.0-rc1 rc release for Dapr runtime  
- [x] Cut the 1.0.0-rc1 rc release for CLI
- [x] Update proto and cut the rc1 release for Java SDK (Artur)
- [x] Update proto and cut the rc1 release for .Net SDK (Vinaya)
- [x] Create devel Helm chart for RC1 (Young Bu / Nghia)
- [x] Create instructions for validation users, with upgrade path (Young Bu / Nghia) 
- [x] Share RC build

11/16 Milestone's date
- [x] Fix all bugs
- [x] Create dashboard RC release 0.4.0-rc.1 (Artur)
- [x] Test and validate latest dashboard RC (Artur).
- [x] Test [Certificate export and Kubernetes upgrade path](https://github.com/dapr/docs/tree/master/howto/deploy-k8s-prod#updating-the-control-plane-pods).
- [x] Test and validate quickstarts in Dawin (Yaron, MarkC)
- [X] Test and validate quickstarts in Linux k8s (Yaron)
- [x] Test and validate quickstarts in Linux self-hosted (Yaron)
- [x] ~~Test and validate quickstarts in Linux ARM64 k8s and self-hosted (Charlie)~~ Quickstarts not currently built for ARM64 (dapr/quickstarts#327)
- [x] Test and validate quickstarts in Windows (Hal, MarkF)
- [x] Test azure-function-extensions (Vinaya)
- [x] Release azure-function-extensions (Vinaya)
- [x] Test (but don't release) dapr-workflows (Yaron)
- [x] Update proto clients in cpp-sdk (Charlie)
- [x] Update proto clients in js-sdk (Young Bu)
- [x] Update proto clients in rust-sdk (Young Bu)
- [x] Update proto clients in python-sdk (Mukundan)
- [x] Test and validate the .NET SDK - run through samples (Vinaya)
- [x] Test and validate the .Java SDK release 0.10.0-rc1 - run through integration tests and samples (Artur)
- [x] Test and validate the python SDK release - run through samples (Mukundan)
- [X] Test and validate the go SDK release  - run through samples (MarkC)
- [x] Add communication about OpenCensus deprecation in blog (MarkF / Ori)
- [x] Validate app upgrade from 0.11.x to 1.0.0-rc.1 (Artur)
- [x] Upgrade Longhaul tests to 1.0.0-rc.1 (Charlie)
- [x] Validate Longhaul metrics (Charlie) - longhaul metrics has not been published for weeks.
- [x] Verify breaking changes section in release notes (Hal)
- [x] Release dapr dashboard (Artur)
- [x] Update dashboard version in Helm Charts (Artur)
- [x] Manually update Helm Charts in release branch after dashboard Helm Chart is updated (Artur)
- [x] Release new RC for dapr/cli (Mukundan / Nghia)
- [x] Release cpp-sdk (Charlie)
- [x] Release js-sdk (Young Bu)
- [x] Release rust-sdk (Young Bu): not using Cargo yet.
- [x] Release python SDK (Mukundan/Young Bu): no docs for Python SDK yet.
- [X] Release Go SDK and docs (MarkC)
- [X] Release dotnet SDK and release nuget packages (Vinaya)
- [x] Create 1.0.0-rc1 branch and for docs in the repos (Ori)
- [x] Create release-1.0 branch for quickstarts, update version tag in the images, create v1.0.0-rc1 tag and update the readme in master (Artur)
- [x] Release 0.10.0 version of java-sdk (Artur)
- [x] Generate new Java docs based on the release version of the Java SDK and push to master (Artur)
- [x] Update Java SDK's README.md to refer to latest version. (Artur)
- [x] Announcement email and Twitter post and **blog**  (Ori)
- [x] Merge (NOT SQUASH MERGE) back release-1.0 branch into master for required repos (Artur)

RELEASE NOTE: NOT APPLICABLE
