### ISSUE TITLE
v1.0.0 Milestone 2 End Game

### ISSUE THREAD

**Issue by wcs1only** [dapr/dapr#2575]
End game Lead: @wcs1only 
End game buddy: @artursouza 

This is the schedule for the v1.0.0 Milestone 2 release

12/11 11:59 PM PST code freeze for the release
12/14 Preview build date

- [x] Code freeze at 11:59 pm 12/11
- [x] No P0 issues before code freeze.
- [x] E2E and perf tests are passing. (Known perf test failures, deemed not a blocker. Known E2E failure not a blocker).
- [x] Merge master into release-1.0 branch for component-contrib (@wcs1only)
- [x] Cut 1.0.0-rc2 release for component-contrib (@wcs1only)
- [x] Update component-contrib pkg to 1.0.0-rc2 in dapr/dapr master branch (@wcs1only)
- [x] Create dashboard RC release 0.5.0-rc.1 (@artursouza).
- [x] Test and validate latest dashboard RC (@artursouza).
- [x] Create dashboard release 0.5.0 (@artursouza)
- [x] Update helm chart versions.
- [x] Merge master release-1.0 branches for Dapr runtime (@wcs1only)
- [x] Merge master release-1.0 release branches for CLI (@tcnghia)
- [x] Cut the 1.0.0-rc2 rc release for Dapr runtime  (@wcs1only)
- [x] Cut the 1.0.0-rc3 rc release for CLI (@wcs1only)
- [x] Update proto and cut the rc2 release for Java SDK (@artursouza)
- [x] Update proto and cut the rc2 release for .Net SDK (@vinayada1)
- [x] Validate devel Helm chart for RC2 (@tcnghia)
- [x] Share RC build.  Communicate Dapr uninstall steps to committed customers. Must have new CLI (@yaron2, @artursouza, @msfussell )
- [x] Send dapr runtime/cli to vscode dev containers team (Phil Hoff, @mukundansundar )
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. (@wcs1only, @artursouza, @mchmarny) (PR created: https://github.com/dapr/dapr/pull/2585) (Be sure to add breaking changes guide for dotnet, and java SDKs)
-----
12/15 Milestone's date
- [x] Update longhaul tests dotnet SDK version (@wcs1only)
- [x] Update longhaul tests Dapr runtime version (@wcs1only)
- [x] Fix all bugs
- [x] Test [Certificate export and Kubernetes upgrade path](https://github.com/dapr/docs/tree/master/howto/deploy-k8s-prod#updating-the-control-plane-pods).
- [x] Test and validate quickstarts in Darwin (@yaron2, @halspang)
- [x] Test and validate quickstarts in Linux k8s (@yaron2)
- [x] Test and validate quickstarts in Linux self-hosted (@yaron2)
- [x] Test and validate quickstarts in Linux ARM64 k8s and self-hosted (@wcs1only )
- [x] Test and validate quickstarts in Windows (@halspang )
- [N/A] Release azure-function-extensions (@vinayada1)
- [x] Update proto clients in cpp-sdk (@wcs1only)
- [x] Update proto clients in js-sdk (@tcnghia)
- [x] Update proto clients in rust-sdk (@tcnghia)
- [x] Update proto clients in python-sdk (@artursouza )
- [x] Test and validate the .NET SDK - run through samples (@vinayada1 )
- [x] Test and validate the .Java SDK release 1.0.0-rc2 - run through integration tests and samples (@artursouza )
- [x] Test and validate the python SDK release - run through samples (@artursouza)
- [x] Test and validate the go SDK release  - run through samples (@mchmarny)
-----
12/16
- [x] Verify breaking changes section in release notes (@halspang)
- [x] Test azure-function-extensions (@vinayada1 )
- [x] Validate app upgrade from 1.0.0-rc.1 to 1.0.0-rc.2 (Need to validate HA mode)(@mchmarny  )
- [x] Validate Longhaul metrics (@wcs1only)
---
- [x] Ensure the docs are clear about using the correct CLI version (1.0.0-rc.3) (@mchmarny)
- [x] **BLOCKING** Understand E2E test failures for the last 48 hours (@wcs1only)
- [x] Release cpp-sdk (@wcs1only)
- [x] Release js-sdk (@tcnghia )
- [x] Release rust-sdk (@tcnghia ): 
- [X] Release python SDK (@artursouza): no docs for Python SDK yet.
- [x] Release Go SDK and docs (@mchmarny)
- [x] Release dotnet SDK and release nuget packages (@vinayada1)
- [x] Create new release 1.0.0-rc3 branch and for docs in the repos (@orizohar, @AaronCrawfis)
- [x] Merge master into release-1.0 branch for quickstarts, update version tag in the images, create v1.0.0-rc2 tag and **update the readme** in master (@wcs1only)
- [x] Make sure the release notes are copied into the github release description at https://github.com/dapr/dapr/releases (@orizohar)
- [x] Release dapr-workflows (@yaron2)
- [x] Generate new Java docs based on the release version of the Java SDK (@artursouza )
- [x] Announcement email and Twitter post and **blog**  (@orizohar )
- [x] Merge (NOT SQUASH MERGE) back release-1.0 branch into master for required repos (@wcs1only )

RELEASE NOTE: NOT APPLICABLE
