### ISSUE TITLE
1.0.0-rc.3 Endgame Milestone

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#2724]
End game Lead: @yaron2 
End game buddy: @artursouza 

This is the schedule for the v1.0.0 Milestone 2 release

1/27 12:00 PM PST code freeze for the release

- [x] Code freeze at 12:00 pm 1/27
- [x] No P0 issues before code freeze.
- [x] E2E and perf tests are passing. (Known perf test failures, deemed not a blocker. Known E2E failure not a blocker).
- [x] Merge master into release-1.0 branch for component-contrib (@yaron2)
- [x] Cut 1.0.0-rc3 release for component-contrib (@wcs1only)
- [x] Update component-contrib pkg to 1.0.0-rc3 in dapr/dapr master branch (@yaron2)
- [x] Create dashboard RC release 0.6.0-rc.1 (@artursouza).
- [x] Test and validate latest dashboard RC (@artursouza).
- [x] Create dashboard release 0.6.0 (@artursouza)
- [x] Update helm chart versions (@yaron2)
- [x] Merge master release-1.0 branches for Dapr runtime (@yaron2 @artursouza )
- [x] Merge master into release-1.0 branche for CLI (@mukundansundar )
- [x] Cut the 1.0.0-rc3 rc release for Dapr runtime  (@yaron2 @artursouza )
- [x] Cut the 1.0.0-rc4 rc release for CLI (@mukundansundar )
- [x] Update proto and cut the rc3 release for Java SDK (@artursouza)
- [x] Update proto and cut the rc4 release for .Net SDK (@vinayada1)
- [x] Share RC build.  Communicate Dapr uninstall steps to committed customers. Must have new CLI (@yaron2, @artursouza, @msfussell )
- [x] Send dapr runtime/cli to vscode dev containers team (Phil Hoff, @mukundansundar )
-----
1/27 Milestone's date
- [x] Update longhaul tests dotnet SDK version (@wcs1only)
- [x] Update longhaul tests Dapr runtime version (@wcs1only)
- [x] Test [Certificate export and Kubernetes upgrade path](https://github.com/dapr/docs/tree/master/howto/deploy-k8s-prod#updating-the-control-plane-pods). (@yaron2)
- [x] Test and validate quickstarts in Darwin (@wcs1only)
- [x] Test and validate quickstarts in Linux k8s (@wcs1only )
- [x] Test and validate quickstarts in Linux self-hosted (@yaron2)
- [x] Test and validate quickstarts in Linux ARM64 k8s and self-hosted (@artursouza  )
- [x] Test and validate quickstarts in Windows (@karishma-chawla  )
- [x] Update proto clients in cpp-sdk (@wcs1only)
- [x] Update proto clients in js-sdk (@tcnghia, PR: https://github.com/dapr/js-sdk/pull/71)
- [x] Update proto clients in rust-sdk (@tcnghia, PR: https://github.com/dapr/rust-sdk/pull/37)
- [x] Update proto clients in python-sdk (@wcs1only )
- [x] Test and validate the .NET SDK - run through samples (@vinayada1 )
- [x] Test and validate the .Java SDK release 1.0.0-rc3 - run through integration tests and samples (@artursouza )
- [x] Test and validate the python SDK release - run through samples (@wcs1only)
- [x] Test and validate the Go SDK release  - run through samples (@yaron2)
- [x] Create [release notes](https://github.com/dapr/dapr/tree/master/docs/release_notes) - CLI, Dapr, .NET SDK, Java SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. (@yaron2, @artursouza) (Be sure to add breaking changes guide for dotnet, and java SDKs)
-----
2/1
- [x] Release and test azure-function-extensions (@vinayada1)
- [x] Verify breaking changes section in release notes (@halspang)
- [x] Validate Longhaul metrics (@wcs1only)
- [x] Ensure the docs are clear about using the correct CLI version (1.0.0-rc.4) (@orizohar )
- [x] Release cpp-sdk (@wcs1only)
- [x] Release js-sdk (@tcnghia )
- [x] Release rust-sdk (@tcnghia )
- [x] Release python SDK (@wcs1only)
- [x] Release Go SDK and docs (@yaron2)
- [x] Release Java SDK and docs (@artursouza )
- [x] Release PHP SDK and docs (@withinboredom  )
- [x] Release dotnet SDK rc.5 and release nuget packages (@vinayada1)
- [x] Create new release for 1.0 branch for docs in the repos (@orizohar, @AaronCrawfis)
- [x] Make rc.3 in docs visible in dropdown (@orizohar, @AaronCrawfis)
- [x] Merge master into release-1.0 branch for quickstarts, update version tag in the images, create v1.0.0-rc3 tag and **update the readme** in master (@wcs1only)
- [x] Make sure the release notes are copied into the github release description at https://github.com/dapr/dapr/releases (@orizohar)
- [x] Release dapr-workflows (@yaron2)
- [ ] Generate new Java docs based on the release version of the Java SDK (@artursouza )
- [x] Merge (NOT SQUASH MERGE) back release-1.0 branch into master for required repos (@yaron2 @artursouza  )

RELEASE NOTE: NOT APPLICABLE
