### ISSUE TITLE
Iteration Plan for Sept 2019

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#359]
This plan captures our work in **September**. This is two, 2-week sprints. 
Sprint 1 - Start 9th Sept - Eng resourcing: Runtime 2.5 dev, SDK 0.5
Sprint 2 - Start 23rd Sept - Eng resourcing: Runtime 2.5, SDK 1.0
Total 4 weeks of coding

*Iteration Master:* @msfussell  

## Key scenarios for this iteration (priority order)

1) Security scenarios including secure communication between Actions and secrets in bindings
2) End to End Testing scenarios
3) Feature parity between development environment capabilities and Kubernetes
4) Continue to improve diagnostics and distributed tracing
5) Binding with statestores, resources and pub/sub. Priority order is: 1) on-premises, 2) Azure and 3) other clouds (AWS, GCP)
6) Improve documentation and first draft of public website

### Endgame
Sept 20th, 2019: Endgame begins

### Endgame
Oct 7th, 2019: Endgame begins
Oct 10th, 2019: Endgame complete

### Spec
- [ ] https://github.com/actionscore/spec/issues/19 Add secrets building block spec
- [ ] https://github.com/actionscore/spec/issues/16 Standard key namespace and scheme for storage

### Runtime

State
- [ ] https://github.com/actionscore/actions/issues/361 Support concurrency and consistency models in Cosmos DB state store
- [ ] https://github.com/actionscore/actions/issues/360 Support concurrency and consistency models in Redis state store
- [ ] https://github.com/actionscore/actions/issues/288 Rename pub-sub redis password to redisPassword
- [ ] https://github.com/actionscore/actions/issues/85 Default concurrency model in state management

Testing
- [ ] https://github.com/actionscore/actions/issues/343 Define Test Infra structure for E2E test
- [ ] https://github.com/actionscore/actions/issues/334 Define Conformance Tests
- [ ] https://github.com/actionscore/actions/issues/345 Define long-running(synthetic test) environment
- [ ] https://github.com/actionscore/actions/issues/335 Define E2E Tests. Test Plan
- [ ] https://github.com/actionscore/actions/issues/375 Implement Test Infra structure for E2E test
- [ ] https://github.com/actionscore/actions/issues/358 Implement E2E tests
- [ ] https://github.com/actionscore/actions/issues/98 standalone automated infra to support automated testing

Diagnostics
- [ ] https://github.com/actionscore/actions/issues/289 Troubleshooting guide
- [ ] https://github.com/actionscore/actions/issues/325 Allow to set sidecar log level in Kubernetes using annotations
- [ ] https://github.com/actionscore/actions/issues/326 Allow Helm Chart to set log level for all Actions system pods

Security
- [ ] https://github.com/actionscore/actions/issues/363 Components - Implement pluggable Secret Stores
- [ ] https://github.com/actionscore/actions/issues/364 In-Transit encryption for gRPC Actions-to-Actions
- [ ] https://github.com/actionscore/actions/issues/374 Components - Enable Kubernetes Secret Store integration

#Actors
- [ ] https://github.com/actionscore/actions/issues/195 Drain in-flight call for an actor if needs to be moved after rebalancing.
- [ ] https://github.com/actionscore/actions/issues/183 Add end to end tests for turn based concurrency for Actors in actions runtime.

### CLI
- [ ] https://github.com/actionscore/cli/issues/49 CLI improvements for preview kit
- [ ] https://github.com/actionscore/cli/issues/57 actions publish payload isn't working on Windows cmd terminal
- [ ] https://github.com/actionscore/cli/issues/49 Support runtime versioning and CLI versioning
- [ ] https://github.com/actionscore/cli/issues/60 "Actions List" gets out out sync with what it thinks is running and what actually is running as a process
- [ ] https://github.com/actionscore/cli/issues/50 Support --uninstall option to clean up
- [x] https://github.com/actionscore/cli/issues/61 Add profiling flags to the run command

### Preview Kit
- [ ] https://github.com/actionscore/actions/issues/321 Document the common release process and create release automation

### .NET SDK
- [ ] https://github.com/actionscore/dotnet-sdk/issues/54 Extend Distributed Tracing Header into Actor SDK
- [ ] https://github.com/actionscore/dotnet-sdk/issues/53 Use Query all statenames api when implemented in Actions runtime.
- [ ] https://github.com/actionscore/dotnet-sdk/issues/8 Create test infrastructure for testing CS SDK with Actions
- [ ] https://github.com/actionscore/dotnet-sdk/issues/9 Add test for C# actor runtime components with Actions runtime
- [ ] https://github.com/actionscore/actions/issues/31 Actor specific end to end tests for daily test runs and for CI/CD

### Engineering Systems
- [ ] https://github.com/actionscore/actions/issues/321 Document the common release process and create release automation
- [ ] https://github.com/actionscore/actions/issues/82 ESRP Onboarding
- [ ] #362  Generate helm manifest for each specific docker image version via CI
- [ ] https://github.com/actionscore/actions/issues/378 List packages used in actions, its author, its support/release cadence & why its needed

## Sprint 2 booked plan items

Legend of annotations:

|Mark | Description|
|------|-----------|
| 🏃 | work in progress|
| ✋ | blocked task|
| 💪 | stretch goal for this iteration|
| 🔴 | missing issue reference|
| 🔵 | more investigation required to remove uncertainty|
| ⚫️ | under discussion within the team|
