### ISSUE TITLE
v1.4.3 Hotfix Release Checklist

### ISSUE THREAD

**Issue by berndverst** [dapr/dapr#3743]
- [x] Create the `v1.4.3-rc.1` Hotfix release (code changes) and test it
- [x] Create `v1.4.3-rc.1` Tag [@artursouza]
- [x] Performance tests passing  [@artursouza]
- [x] End to End tests passing on Linux and Windows [@artursouza]
- [ ] ~Update the longhaul tests to use `1.4.3` [@halspang]~
- [x] One-off: Run Kubernetes Quickstart on Arm64 Cluster [@berndverst]
- [x] Create `v1.4.3` Tag [@artursouza]
- [x] Update the documentation: Latest version & versions in supported releases [@greenie-msft]
- [x] Announce the hotfix release [@orizohar]
