### ISSUE TITLE
v1.6.0 Release Planning

### ISSUE THREAD

**Issue by dmitsh** [dapr/dapr#3908]
Release Coordinator: @dmitsh
Release Buddy: @amulyavarote

Preflight check: 01/06/2022
Code freeze: 01/13/2022
Endgame starts: 01/14/2022
Release date: 01/20/2022

## Priorities
* Improving e2e test stability @dmitsh 
* CNCF onboarding activities
  * @artursouza , @greenie-msft , @msfussell , @willtsai , @yaron2 
* Resiliency - phase 1 (out of scope of 1.6)
  * @pkedy @halspang
* More stable components
  * Azure EventHub PubSub
    * @mukundansundar (PR merged, conformance test debugging, cert test? Goal - promote to beta)
  * Azure blob storage binding (paused)
    * @berndverst 
  * Azure EventHub binding
    * @tanvigour (PR reviewed, cert test PR WIP. Goal - promote to beta)
  * Azure ServiceBus binding (WIP)
    * @halspang 
  * Azure CosmosDB binding (Done)
    * @berndverst
  * ~Kafka binding (requires further discussion) ~
  * MQTT PubSub
    * Shivam (MQTT to be promoted to beta)
  * RabbitMQ PubSub
    * @dmitsh 
* Add missing features to SDKs
  * Query State API (all)
    * go-sdk @dmitsh (Done)
    * java-sdk @mukundansundar  - alpha stage, HTTP only
    * js-sdk @XavierGeerinck (WIP)
    * python-sdk @berndverst 
    * dotnet-sdk @halspang 
    * php-sdk @withinboredom (?)
    * rust-sdk - autogenerated
    * cpp-sdk - autogenerated
  * Actor reminder/timer TTL (all)
    * go-sdk @dmitsh (Done)
    * java-sdk  Giovds
    * js-sdk @XavierGeerinck (WIP)
    * python-sdk @berndverst 
    * dotnet-sdk @halspang 
    * php-sdk @withinboredom (?)
    * rust-sdk - autogenerated
    * cpp-sdk - autogenerated
  * PubSub routing (Java, JS, Go)
    * go-sdk @pkedy @dmitsh 
    * java-sdk @pkedy @halspang 
    * js-sdk @XavierGeerinck 
  * Configuration API (all)
    * go-sdk @yaron2 
    * java-sdk @pravinpushkar
    * js-sdk @XavierGeerinck  (WIP)
    * python-sdk @amulyavarote
    * dotnet-sdk @halspang (?)
    * php-sdk @withinboredom (?)
    * rust-sdk - autogenerated
    * cpp-sdk - autogenerated
    
## Milestones
Dapr: https://github.com/dapr/dapr/milestone/12
Python-SDK: https://github.com/dapr/python-sdk/milestone/5
JS-SDK: https://github.com/dapr/js-sdk/milestone/1
CLI: https://github.com/dapr/cli/milestone/7
PHP-SDK: https://github.com/dapr/php-sdk/milestone/9
Docs: https://github.com/dapr/docs/milestone/9
Components-contrib: https://github.com/dapr/components-contrib/milestone/7
Dotnet-SDK: https://github.com/dapr/dotnet-sdk/milestone/10
Go-SDK: https://github.com/dapr/go-sdk/milestone/4
Java-SDK: https://github.com/dapr/java-sdk/milestone/4
Dashboard: not released

**Comment by amulyavarote** [comment]
- Release buddy!

**Comment by artursouza** [comment]
@msfussell @yaron2 @greenie-msft See priorities for this release highlighted above.

**Comment by dmitsh** [comment]
Preflight checklist:

* [ ]  Can any preview features be made stable (requires all SDKs to have implementation)?
* [ ]  Can alpha APIs be made stable?
* [ ]  For any new runtime feature are there tracking issues in all SDKs for implementation?
* [ ]  Are the long haul tests successful?
