### ISSUE TITLE
v1.4.4 Hotfix Release Checklist

### ISSUE THREAD

**Issue by berndverst** [dapr/dapr#3938]
- [x] Create the `v1.4.4-rc.1` Hotfix release (code changes) and test it
- [x] Create `v1.4.4-rc.1` Tag [@berndverst ]
- [x] ~Performance tests passing  [@artursouza]~
- [x] ~End to End tests passing on Linux and Windows [@berndverst]~
- [x] ~Update the longhaul tests to use `1.4.4` [@halspang]~
- [x] Release notes
- [x] Create `v1.4.4` Tag [@berndverst]
- [x] Update the documentation: Latest version & versions in supported releases [@greenie-msft]
- [x] Announce the hotfix release [@greenie-msft ]

**Comment by berndverst** [comment]
PRs required for this Hotfix release.

Make sure to use **release-1.4** branches only!

## Components Contrib
- [ ] https://github.com/dapr/components-contrib/pull/1180 (cherry-pick from master)
- [ ] https://github.com/dapr/components-contrib/pull/1232 (cherry-pick from master)
- [ ] https://github.com/dapr/components-contrib/pull/1329 (cherry-pick from master)
- [ ] https://github.com/dapr/components-contrib/pull/1278 (cherry-pick from master)

## Dapr/Dapr
- [ ] https://github.com/dapr/dapr/pull/3892 (cherry-pick from master)
- [ ] https://github.com/dapr/dapr/pull/3901 (cherry-pick from master)
- [ ] https://github.com/dapr/dapr/pull/3923
- [ ] https://github.com/dapr/dapr/pull/3728 (cherry-pick from master)

Create new Components-Contrib tag and release.
- [ ] RC tag created
- [ ] Update dapr/dapr go.mod to point to the components contrib release candidate tag
- [ ] Release tag created
- [ ] Release created
