### ISSUE TITLE
v1.5.1 Hotfix Release Checklist

### ISSUE THREAD

**Issue by berndverst** [dapr/dapr#3939]
- [x] Create the `v1.5.1-rc.1` Hotfix release (code changes) and test it
- [x] Create `v1.5.1-rc.1` Tag [@berndverst ]
- [x] ~Performance tests passing  [@artursouza]~
- [x] ~End to End tests passing on Linux and Windows [@berndverst]~
- [x] Notify users to try RC1
- [x] Update the longhaul tests to use `1.5.1-rc.1` [@halspang]
- [x] Release notes
- [x] Wait until Dec 6th for feedback on RC1
- [x] Create `v1.5.1` Tag [@berndverst]
- [x] Update the documentation: Latest version & versions in supported releases [@greenie-msft]
- [x] Announce the hotfix release [@greenie-msft ]

**Comment by berndverst** [comment]
PRs required for this Hotfix release.

Make sure to use **release-1.5** branches only!

## Components Contrib
- [ ] https://github.com/dapr/components-contrib/pull/1329 (cherry-pick from master)
- [ ] https://github.com/dapr/components-contrib/pull/1278 (cherry-pick from master)

## Dapr/Dapr
- [ ] https://github.com/dapr/dapr/pull/3919 (**should be merged back to master**)
- [ ] https://github.com/dapr/dapr/pull/3892 (cherry-pick from master)
- [ ] https://github.com/dapr/dapr/pull/3901 (cherry-pick from master)

## CLI
- [ ] https://github.com/dapr/cli/pull/835 (cherry-pick from master)

Create new Components-Contrib tag and release.
- [ ] RC tag created
- [ ] Update dapr/dapr go.mod to point to the components contrib release candidate tag
- [ ] Release tag created
- [ ] Release created

**Comment by berndverst** [comment]
If this issue gets addressed in time we will also cherry-pick it into the hotfix release:
https://github.com/dapr/dapr/issues/3930

**Comment by darren-wang** [comment]
@berndverst we found resource leakage in tests before adoption of dapr, now we are waiting the hotfix version, can you cherry pick this pr in 1.5.1? 

https://github.com/dapr/dapr/pull/3890

Now our adoption process is stuck due to this bug.

**Comment by yaron2** [comment]
> @berndverst we found resource leakage in tests before adoption of dapr, now we are waiting the hotfix version, can you cherry pick this pr in 1.5.1?
> 
> #3890
> 
> Now our adoption process is stuck due to this bug.

See my comment on the PR: I need to understand if this is a regression (have you not seen this with 1.4.x), and want to understand exactly what the impact is and under which conditions it occurs.

**Comment by berndverst** [comment]
@rabollin doesn't look like anyone is working on it yet, so it isn't likely to make it into 1.5.1. Hopefully someone will take a look for 1.6.

**Comment by berndverst** [comment]
Yes @darren-wang per the discussion on https://github.com/dapr/dapr/pull/3890 and the support from @yaron2 for cherry-picking this, it will be included in the 1.5.1 hotfix release.

**Comment by darren-wang** [comment]
> Yes @darren-wang per the discussion on #3890 and the support from @yaron2 for cherry-picking this, it will be included in the 1.5.1 hotfix release.

Hi, when is v1.5.1 planned to release?

**Comment by yaron2** [comment]
> > Yes @darren-wang per the discussion on #3890 and the support from @yaron2 for cherry-picking this, it will be included in the 1.5.1 hotfix release.
> 
> Hi, when is v1.5.1 planned to release?

Dec 6.
