### ISSUE TITLE
v1.7.2 Release Hotfix Checklist

### ISSUE THREAD

**Issue by amulyavarote** [dapr/dapr#4548]
This is for the v1.7.0 branch

## Checklist
- [ ] ~Create the `v1.7.2-rc.1` Hotfix release (code changes) and test it~
- [ ] ~Create `v1.7.2-rc.1` Tag [@]~
- [ ] ~Performance tests passing  [@]~
- [ ] ~End to End tests passing on Linux and Windows [@]~
- [ ] ~Notify users to try RC1~
- [ ] ~Update the longhaul tests to use `1.7.2-rc.1` [@]~
- [x] Write and review release notes [@artursouza]
- [x] Create `v1.7.2` Tag [@artursouza]
- [x] Update the documentation: Latest version & versions in supported releases [@greenie-msft]
- [x] Push new tag in installer-bundle repo.[@shivamkm07 ]
- [x] Announce the hotfix release on Discord Announcements channel [@greenie-msft ]

**Comment by amulyavarote** [comment]
PRs required for this Hotfix release.

Make sure to use release-1.5 branches only!

Dapr/Dapr:

https://github.com/dapr/dapr/pull/4545

**Comment by greenie-msft** [comment]
Docs PR for updating the version to 1.7.2 - https://github.com/dapr/docs/pull/2390

**Comment by berndverst** [comment]
All items in the checklist are done @amulyavarote -- but not the docs update and announcing the hotfix.

The hotfix is already published.
