### ISSUE TITLE
v1.7.3 Release Hotfix Checklist

### ISSUE THREAD

**Issue by johnewart** [dapr/dapr#4625]
- [ ] ~~Create the v1.7.3-rc.1 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.7.3-rc.1 Tag [@]~~
- [ ] ~~Performance tests passing [@]~~
- [x] End to End tests passing on Linux and Windows [@]
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.7.3-rc.1 [@]~~
- [x] Write release notes [@johnewart]
- [x] Review release notes [@artursouza]
- [x] Create v1.7.3 Tag [@]
- [x] Update the documentation: Latest version & versions in supported releases [@greenie-msft]
- [x] Push new tag in installer-bundle repo. [@shivamkm07]
- [x] Announce the hotfix release on Discord Announcements channel [@greenie-msft]

**Comment by johnewart** [comment]
This has been released, I am going to close this issue
