### ISSUE TITLE
v1.7.4 Release Hotfix Checklist

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#4687]
- [ ] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] Security vulnerability
   - [ ] Regression that does not have a work around
   - [ ] Broken mainline scenario that has a missing test case
- [ ] ~~Create the v1.7.4-rc.1 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.7.4-rc.1 Tag [@]~~
- [X] Performance tests passing [@]
- [X] End to End tests passing on Linux and Windows [@]
- [ ] New test case written to catch future occurences
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.7.4-rc.1 [@]~~
- [X] Write release notes [@italypaleale]
- [X] Review release notes [@artursouza]
- [X] Create v1.7.4 Tag [@artursouza]
- [ ] Update the documentation: Latest version & versions in supported releases [@greenie-msft]
- [ ] Push new tag in installer-bundle repo. [@shivamkm07]
- [ ] Announce the hotfix release on Discord Announcements channel [@greenie-msft]
