### ISSUE TITLE
1.8.1 Hotfix release checklist

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#4914]
- [X] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] Security vulnerability
   - [X] Regression that does not have a work around: https://github.com/dapr/components-contrib/issues/1881
   - [ ] Broken mainline scenario that has a missing test case
- [ ] ~~Create the v1.8.1-rc.1 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.8.1-rc.1 Tag [@]~~
- [x] Performance tests passing [@]
- [x] End to End tests passing on Linux and Windows [@]
- [X] New test case written to catch future occurrences
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.8.1-rc.1 [@]~~
- [X] Write release notes [@italypaleale] https://github.com/dapr/dapr/pull/4916
- [x] Review release notes [@artursouza]
- [x] Create v1.8.1 Tag [@artursouza]
- [x] Update the documentation: Latest version & versions in supported releases [@greenie-msft]
- [X] Push new tag in installer-bundle repo. [@shivamkm07] https://github.com/dapr/installer-bundle/releases/tag/v1.8.1
- [x] Announce the hotfix release on Discord Announcements channel [@greenie-msft]

**Comment by ItalyPaleAle** [comment]
1.8.1 was released and all tasks completed
