### ISSUE TITLE
1.8.2 Hotfix release checklist

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#4927]
- [X] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] Security vulnerability
   - [X] Regression that does not have a work around: https://github.com/dapr/dapr/pull/4926
   - [ ] Broken mainline scenario that has a missing test case
- [ ] ~~Create the v1.8.2-rc.1 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.8.2-rc.1 Tag [@]~~
- [ ] Performance tests passing [@]
- [x] End to End tests passing on Linux and Windows [@]
- [ ] New test case written to catch future occurrences:  #4926 @ItalyPaleAle 
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.8.2-rc.1 [@]~~
- [X] Write release notes [@italypaleale]: https://github.com/dapr/dapr/pull/4930
- [X] Review release notes [@yaron2]
- [X] Create v1.8.2 Tag [@yaron2]
- [x] Update the documentation: Latest version & versions in supported releases [@greenie-msft]
- [x] Push new tag in installer-bundle repo. [@shivamkm07]
- [ ] Announce the hotfix release on Discord Announcements channel [@greenie-msft]

**Comment by shivamkm07** [comment]
Installer bundle v1.8.2 is released: https://github.com/dapr/installer-bundle/releases/tag/v1.8.2
