### ISSUE TITLE
1.8.3 Hotfix release checklist

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#4943]
- [X] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] Security vulnerability
   - [X] Regression that does not have a work around: https://github.com/dapr/dapr/pull/4942
   - [ ] Broken mainline scenario that has a missing test case
- [ ] ~~Create the v1.8.3-rc.1 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.8.3-rc.1 Tag [@]~~
- [ ] Performance tests passing [@]
- [x] End to End tests passing on Linux and Windows [@]
- [x] New test case written to catch future occurrences:  #4942 
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.8.3-rc.1 [@]~~
- [x] Write release notes [@italypaleale]: https://github.com/dapr/dapr/pull/4942
- [x] Review release notes [@artursouza or @yaron2 ]
- [x] Create v1.8.3 Tag [@artursouza or @yaron2 ]
- [x] Update the documentation: Latest version & versions in supported releases [@greenie-msft or @nyemade-uversky ]
- [x] Push new tag in installer-bundle repo. [@shivamkm07]
- [x] Announce the hotfix release on Discord Announcements channel [@nyemade-uversky ]

**Comment by shivamkm07** [comment]
Installer bundle 1.8.3 released: https://github.com/dapr/installer-bundle/releases/tag/v1.8.3

**Comment by ItalyPaleAle** [comment]
All done
