### ISSUE TITLE
1.8.4 Hotfix release checklist

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#4995]
- [X] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [X] Security vulnerability: https://github.com/dapr/components-contrib/pull/1954
   - [X] Regression that does not have a work around: https://github.com/dapr/components-contrib/pull/1957
   - [ ] Broken mainline scenario that has a missing test case
- [ ] ~~Create the v1.8.4-rc.1 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.8.4-rc.1 Tag ~~
- [ ] Performance tests passing [@]
- [ ] End to End tests passing on Linux and Windows [@]
- [X] New test case written to catch future occurrences:  N/A
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.8.4-rc.1~~
- [X] Write release notes [@italypaleale]: https://github.com/dapr/dapr/pull/4994
- [ ] Review release notes [@artursouza or @yaron2 ]
- [ ] Create v1.8.4 Tag [@artursouza or @yaron2 ]
- [ ] Update the documentation: Latest version & versions in supported releases [@greenie-msft or @nyemade-uversky ]
- [ ] Push new tag in installer-bundle repo. [@shivamkm07]
- [ ] Announce the hotfix release on Discord Announcements channel [@nyemade-uversky ]

**Comment by ItalyPaleAle** [comment]
Closing as complete
