### ISSUE TITLE
1.9.3 Hotfix release checklist

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#5452]
- [x] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] Security vulnerability
   - [X] Regression that does not have a work around: https://github.com/dapr/dapr/pull/5455
   - [ ] Broken mainline scenario that has a missing test case
- [ ] ~~Create the v1.9.3-rc.1 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.9.3-rc.1 Tag ~~
- [x] Performance tests passing: https://github.com/dapr/dapr/actions/runs/3395935019
- [x] End to End tests passing on Linux and Windows: https://github.com/dapr/dapr/actions/runs/3395934010
- [X] New test case written to catch future occurrences: [@johnewart] https://github.com/dapr/dapr/pull/5455
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.9.3-rc.1~~
- [x] Write release notes [@italypaleale]
- [X] Review release notes [@artursouza or @yaron2 ]
- [x] Create v1.9.3 Tag [@artursouza or @yaron2 ]
- [x] Backport fixes into master branch: https://github.com/dapr/dapr/pull/5461
- [ ] Update the documentation: Latest version & versions in supported releases [@greenie-msft or @nyemade-uversky ]
- [x] Push new tag in installer-bundle repo. [@shivamkm07]
- [ ] Announce the hotfix release on Discord Announcements channel [@greenie-msft or @nyemade-uversky ]

**Comment by ItalyPaleAle** [comment]
Closed as complete
