### ISSUE TITLE
1.9.4 Hotfix release checklist 

### ISSUE THREAD

**Issue by addjuarez** [dapr/dapr#5536]
- [x] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] Security vulnerability
   - [x] Regression that does not have a work around: https://github.com/dapr/dapr/pull/5534
   - [ ] Broken mainline scenario that has a missing test case
- [ ] ~~Create the v1.9.4 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.9.4-rc.1 Tag~~
- [x] Performance tests passing: https://github.com/dapr/dapr/actions/runs/3491327743
- [x] End to End tests passing on Linux and Windows: https://github.com/dapr/dapr/actions/runs/3491329324
- [ ] ~~New test case written to catch future occurrences: -~~
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.9.4-~~
- [x] Write release notes [@addjuarez ]
- [x] Review release notes [@artursouza or @yaron2 ]
- [x] Create v1.9.4 Tag [@artursouza or @yaron2 ]
- [ ] ~~Backport fixes into master branch~~ (Not needed because already fixed in master by updated dependency)
- [x] Update the documentation: Latest version & versions in supported releases [@greenie-msft or @nyemade-uversky]
- [x] Push new tag in installer-bundle repo. [@shivamkm07]
- [x] Announce the hotfix release on Discord Announcements channel [@greenie-msft or @nyemade-uversky ]

**Comment by shivamkm07** [comment]
Installer Bundle 1.9.4 released: https://github.com/dapr/installer-bundle/releases/tag/v1.9.4
