### ISSUE TITLE
[EPIC] Make Bulk Pubsub APIs stable

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#5567]
# Bulk Pubsub APIs (Bulk Publish and Bulk Subscribe)

> If you need more information on what needs to be completed, look in the `guides` directory for relevant guidance.

This issue follows the lifecycle process defined in dapr/proposals and uses the template found [here](https://github.com/dapr/proposals/blob/main/templates/lifecycle.md).
This issue will be used for tracking lifecycle of the Bulk Publish API with relevant issues linked for each lifecycle stage.

# Links

Links to any relevant resources go here:

* Relevant proposal - #2218 
* Existing issues - #5549 

# Acceptance criteria

> For each of the stages, add any specific tasks that need to be completed before this feature reaches that particular stage. If a particular item is *not needed* then a reason should be given.

## Alpha (Target for v1.10)

- [x] Minimum of one core SDK supports this feature (.NET / Python / Go / Java)
  - [x] Java SDK (https://github.com/dapr/java-sdk/issues/778) 
    - [x] Bulk Publish https://github.com/dapr/java-sdk/pull/789
    - [x] Bulk Subscribe https://github.com/dapr/java-sdk/pull/791
  - [ ] JS SDK (https://github.com/dapr/js-sdk/issues/360) [Awaiting Dapr release to be merged]
  - [x] .NET SDK
    - [x] https://github.com/dapr/dotnet-sdk/pull/1001
    - [x] https://github.com/dapr/dotnet-sdk/pull/1009
- [x] Feature documentation added to `dapr/docs` 
  - [x] https://github.com/dapr/docs/issues/2783 ()
  - [x] https://github.com/dapr/docs/issues/2804 
  - [x] https://github.com/dapr/docs/issues/2813
  - [x] https://github.com/dapr/docs/issues/2825
- [x] Telemetry data (metrics) available for this feature Related PR (#5256)
- [x] Issue opened in `dapr/quickstarts` for quickstart examples to be created (https://github.com/dapr/quickstarts/issues/736) (not implementations)
- [x] E2E tests for happy path/critical path (#5256)
- [x] Performance tests exist but do not block builds (considering Bulk Pubsub as optimisation to pubsub)
  - [x] Bulk Publish gRPC #5497 
  - [x] Bulk Subscribe HTTP #5502  
- [x] Implementation optimiazation / fixes on top of #5256 
  - [x] #5368
  - [x] #5367 
  - [x] #5369 
  - [x] #5500 
  - [x] #5501 
  - [x] #5499 
  - [x] #5598
  - [x] dapr/components-contrib#2260
 

Additionally, for **APIs**:

- [x] Both HTTP and gRPC protocols implemented (#5256)
- [x] HTTP API documentation added to the `Reference` section of Dapr documentation (https://github.com/dapr/docs/issues/2783)

Additionally, for **building blocks**:

- [x] Interfaces to be used by `dapr/dapr` code defined and agreed upon (https://github.com/dapr/components-contrib/pull/2126)(#2218)
- ~~[ ] New building block package is defined in `components-contrib` repo [This is not applicable here]~~
- [x] Conformance tests validating the components compliance added (https://github.com/dapr/components-contrib/pull/2126)
- [x] Minimum of _one_ implementation (preferably something already in-use such as Redis if possible to reduce complexity) 
  - [x] https://github.com/dapr/components-contrib/pull/2126 Adds Kafka, ASB and EH (no bulk subscribe) implementation for Bulk Pubsub

## Beta

- [ ] E2E tests are up-to-date and comprehensive
  - [x] #5924 
  - [x] #5923 
  - [x] #5995 
- [ ] SDK spec is updated
- [ ] No major changes to the API have occurred in the last [TBD] time period (releases? months?)
- [ ] Optimizations
    - [x] #5453 
    - [ ] Add a `maxPubCount` and a `maxPubBytes` as metadata fields for Bulk Publish
- [ ] Components changes for Bulk Pubsub
    - [ ] Explore support for bulk subscribe for Azure Event Hubs
    - [ ] Explore support for AWS SNS/SQS for Bulk Pubsub
- [ ] Support in core SDKs
   - [ ] Python
   - [ ] Go
   - [ ] Java
   - [ ] .NET
- [ ] Documentation up-to-date with any new changes since Alpha
- [ ] Quickstarts have been created

Additionally, for **building blocks**:

- [ ] Conformance tests updated to match any API changes that have been made
- [ ] Conformance tests exercise both positive and negative cases 
- [ ] Minimum of two implementations of this building block 
- [ ] Certification tests for implementations 
    - [ ] Apache Kafka
    - [ ] Azure Service Bus
- [ ] APIs that are used in the building block also meet Beta criteria

## Stable 

- [ ] Documentation is complete in `dapr/docs` with any changes since Beta
- [ ] E2E scenarios well defined and comprehensive
- [ ] Performance tests exist and regressions will prevent them from successfully passing
- [ ] Performance data added to documentation (https://docs.dapr.io/operations/performance-and-scalability/)

**Comment by mukundansundar** [comment]
@nyemade-uversky Ideally can move this EPIC out of the 1.10 release tracking board after the release as this issue is going to be open till the API is finally made stable.

**Comment by shubham1172** [comment]
@mukundansundar please check JS-SDK support (under alpha).

**Comment by olitomlinson** [comment]
We have a user on Discord who is trying to use Bulk PubSub (Azure Service Bus), but can't due to hitting message size limits on bulk publish and there doesn't seem to be a good workaround. 

Given that ASB is one of target components to be supported by Bulk, I think this needs looking into. If @shubham1172 could take a look and advise, that would be great. Thanks!

https://discord.com/channels/778680217417809931/901141467840524289/1192429808269938769

Cc @mukundansundar

**Comment by shubham1172** [comment]
@olitomlinson thank you for tagging, this got buried in my GH notifications it seems. I will have a look at it this week (will ask the user to create a GH issue for tracking).

**Comment by javier-aliaga** [comment]
- [x] E2E tests are up-to-date and comprehensive
- [ ] SDK spec is updated
- [x] No major changes to the API have occurred in the last XXX time period (releases? months?)
- [x] Support in core SDKs
   - [x] Python
   - [x] Go
   - [x] Java
   - [x] .NET
- [ ] Documentation up-to-date with any new changes since Alpha
  -  https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-bulk/
  - [x] Missing declarative config https://github.com/dapr/dapr/pull/5662
  - [x] Missing Go and Python client examples (current tests uses http clients)
~- [ ] Quickstarts have been created~ - See https://github.com/dapr/quickstarts/issues/736#issuecomment-1410951229

Additionally, for **building blocks**:

- [x] Conformance tests updated to match any API changes that have been made
- [x] Conformance tests exercise both positive and negative cases 
- [x] Minimum of two implementations of this building block 
- [ ] Certification tests for implementations 
  - [ ] Apache Kafka
  - [ ] Azure Service Bus
- [x]  APIs that are used in the building block also meet Beta criteria

**Comment by WhitWaldo** [comment]
Seems like stable should have checkmarks for each of the SDKs again (given that at least a name update is required to support stable).

The .NET SDK has been updated for the 1.17 release to reflect the stable bulk pubsub API name.
