### ISSUE TITLE
1.9.4 Hotfix release checklist

### ISSUE THREAD

**Issue by RyanLettieri** [dapr/dapr#5574]
- [x] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] Security vulnerability
   - [ ] Regression that does not have a work around
   - [x] Broken mainline scenario that has a missing test case
- [ ] ~~Create the v1.9.4 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.9.4-rc.1 Tag~~
- [ ] Performance tests passing: 
- [ ] End to End tests passing on Linux and Windows: 
- [x] New test case written to catch future occurrences: https://github.com/dapr/components-contrib/pull/2322
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.9.4-~~
- [ ] Write release notes [@addjuarez ]
- [ ] Review release notes [@artursouza or @yaron2 ]
- [ ] Create v1.9.4 Tag [@artursouza or @yaron2 ]
- [ ] Backport fixes into master branch
- [ ] Update the documentation: Latest version & versions in supported releases [@greenie-msft or @nyemade-uversky]
- [ ] Push new tag in installer-bundle repo. [@shivamkm07]
- [ ] Announce the hotfix release on Discord Announcements channel [@greenie-msft or @nyemade-uversky ]

**Comment by yaron2** [comment]
1.9.4 was completed and released.
