### ISSUE TITLE
1.9.5 Hotfix release checklist

### ISSUE THREAD

**Issue by RyanLettieri** [dapr/dapr#5576]
- [x] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] Security vulnerability
   - [ ] Regression that does not have a work around
   - [x] Broken mainline scenario that has a missing test case
- [ ] ~~Create the v1.9.5 Hotfix release (code changes) and test it~~
- [ ] ~~Create v1.9.5-rc.1 Tag~~
- [ ] Performance tests passing: 
- [ ] End to End tests passing on Linux and Windows: 
- [x] New test case written to catch future occurrences: https://github.com/dapr/components-contrib/pull/2322
- [ ] ~~Notify users to try RC1~~
- [ ] ~~Update the longhaul tests to use 1.9.5-~~
- [x] Write release notes [@addjuarez ]
- [x] Review release notes [@artursouza or @yaron2 ]
- [x] Create v1.9.5 Tag [@artursouza or @yaron2 ]
- [ ] Backport fixes into master branch
- [ ] Update the documentation: Latest version & versions in supported releases [@greenie-msft or @nyemade-uversky]
- [ ] Push new tag in installer-bundle repo. [@shivamkm07]
- [ ] Announce the hotfix release on Discord Announcements channel [@greenie-msft or @nyemade-uversky ]

**Comment by yaron2** [comment]
@RyanLettieri we are also tracking this issue: https://github.com/dapr/dapr/issues/5575.

**Comment by nyemade-uversky** [comment]
We're also tracking this bug for the 1.9.5 hotfix: https://github.com/dapr/components-contrib/pull/2310

**Comment by ItalyPaleAle** [comment]
Per Discord, we should track this too: https://github.com/dapr/dapr/pull/5584

**Comment by shivamkm07** [comment]
Installer Bundle 1.9.5 released: https://github.com/dapr/installer-bundle/releases/tag/v1.9.5

**Comment by ItalyPaleAle** [comment]
Closing as complete
