### ISSUE TITLE
v1.10 Endgame

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#5798]
## Release team
Release lead: @nyemade-uversky 
Release lead shadow(s): @msfussell and @greenie-msft 
Perf test lead: @tmacam and @mcandeia 
Long haul test: @tmacam
Build manager: @artursouza

Read about the [Dapr release lifecycle](https://github.com/dapr/community/blob/master/release-process.md)

## Milestone dates
Feature definition starts: 10/17/2022
Feature definition ends: 11/04/2022
Code freeze: 01/27/2023
Endgame starts: 01/30/2023
Endgame ends: 02/10/2023
1.10.0 release: 02/13/2023

Release Tasks:

------------------
ETA for all below: 02/10/2023

- [x] No P0 issues before code freeze.
- [x] Code freeze at 1/30/2022
- [x] Check all new components are registered in dapr/dapr @yaron2 
- [x]  E2E, certification and perf tests are passing @artursouza
- [x] Update components-contrib certification tests go.mods with dapr/dapr 1.10.0-rc.1 commit hash  @berndverst  
- [X] Create release-1.10 branch and cut RC 1.10.0-rc.1 for component-contrib 
- [X] Update dapr/component-contrib pkg to 1.10.0-rc.1 in dapr/dapr master branch 
- [X] Create release-1.10 branch for Dapr runtime 
- [X] Verify helm chart and cut the 1.10.0-rc.1 release for Dapr runtime 
- [X] Create release-1.10 branch for CLI 
- [X] Update dapr/dapr pkg to 1.10.0-rc.1 in dapr/cli release-1.10 branch 
- [X] Cut the 1.10.0-rc.1 release for CLI 
- [X] Notify users about dapr/dapr 1.10.0-rc.1 via Discord @artursouza 
- [x] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. (~This can partially be accomplished by updating the CLI upgrade_test.go~) @shivamkm07 
- [x] Validate dapr init in self hosted mode for RC from GHCR and default registry @DeepanshuA
- [x] Validate dapr init in k8s mode for RC from GHCR and default registry @DeepanshuA 
- [x] Validate renew-certificate command with a cluster with a Dapr enabled app @yaron2
- [x] Create RC for installer-bundle @shivamkm07 
- [x] Validate RC for installer bundle @shivamkm07 
- [x] Update proto and cut the rc release for Java SDK  @artursouza 
- [x] Update proto and cut the rc release for Python SDK  @berndverst 
- [x] Update proto and cut the rc release for Go SDK  @robertojrojas 
- [x] Update proto and cut the rc release for dotnet SDK  @halspang 
- [x] Update proto and cut the rc release for cpp SDK  @pravinpushkar 
- [x] Update proto and cut the rc release for rust SDK @robertojrojas 
- [x] Cut the rc release for Dashboard @artursouza
- [x] Update longhaul tests dotnet SDK version @tmacam
- [x] Update longhaul tests Dapr runtime version @tmacam
- [x] Update quickstarts/tutorials automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS. ~Workflow pulls the latest dapr version before the validations begin~ @artursouza
- [x] Test and validate quickstarts/tutorials  and quickstarts in Linux ARM64 k8s and self-hosted  @robertojrojas
- [x] Test and validate quickstarts/tutorials in Windows @robertojrojas 
- [x] Add quickstart for Workflow Engine in .Net with automation with Mechanical Markdown @RyanLettieri 
- [x] Use `dapr run -f` to service invocation quickstart (per language) @pravinpushkar
- [x] Validate Dapr CLI non-slim scenarios on Windows @shubham1172 
- [x] Validate longhaul metrics @tmacam 
- [x] Test and validate the .NET SDK - run through samples @yash-nisar
- [x] Test and validate the Java SDK - run through samples @artursouza
- [X] Test and validate the Python SDK - run through samples  @berndverst 
- [X] Test and validate the Go SDK - run through samples @robertojrojas 
- [x] Test and validate Dashboard, local mode and kubernetes hosted @artursouza 
- [x] Update certification tests in components-contrib release branch (prior to merge back into master) to use the RC and Go SDK release. @berndverst 
- [x] Confirm with SDK maintainers first, then generate release notes - CLI, Dapr, Contrib, .NET SDK, Java SDK, JS SDK, Python SDK, Go SDK. Check them in release branch before cutting the RC release. @artursouza / @yaron2
- [x] Edit and complete release-notes on HackMD (everyone)
- [x] Verify 1.10 documentation @msfussell
ETA for all above: 02/10/2023

------------------
RELEASE DAY: 02/13/2023
- [x] Release Dashboard @artursouza, update dapr/dapr's helm chart to remove RC suffix
- [x] Verify no breaking changes section in release notes @artursouza
- [x] Merge release notes into release branch @artursouza 
- [x] Release Dapr 1.10 @artursouza 
- [x] Release CLI 1.10 @mukundansundar @yaron2 
- [x] Release Installer Bundle 1.10 @shivamkm07 
- [x] Create blog post @nyemade-uversky 
- [x] Create release-1.10 branch for tutorials, update version tag in the images, create v1.10.0 tag @artursouza  
- [x] For all SDKs, update dapr version and SDK rc version, and check e2e tests (SDK maintainers)
- [ ] Release cpp-sdk @pravinpushkar
- [ ] Release js-sdk @shubham1172 
- [x] Release go-sdk @yaron2 
- [x] Release java-sdk @artursouza 
- [x] Release python-sdk @berndverst 
- [x] Release rust-sdk @artursouza 
- [ ] Release dotnet-sdk and release nuget packages 
- [x] Make sure the release notes are copied into the GitHub release description at https://github.com/dapr/dapr/releases @artursouza 
- [x] Create components-contrib release from Tag. Copy components release notes section into the description of the release. @berndverst 
- [x]  [Not needed anymore] ~In the dapr/dapr master branch, update DEV_CONTAINER_VERSION_TAG in docker/docker.mk to the next release increment. Update the DEV_CONTAINER_CLI_TAG to the latest CLI release. In the same PR also update .devcontainer/devcontainer.json to refer to the new Dev Container version.~ @ItalyPaleAle 
- [x] In the dapr/components-contrib master branch, update dapr/components-contrib/.devcontainer/Dockerfile to reference the updated dapr-dev image tag for the new release. @ItalyPaleAle 
- [x] In the dapr/cli master branch, update dapr/cli/.devcontainer/Dockerfile to reference the updated dapr-dev image tag for the new release. @ItalyPaleAle 
- [x] Update certification tests in components-contrib release branch (prior to merge back into master) to use latest runtime and Go SDK release. @berndverst 
- [x] Generate new Java docs based on the release version of the Java SDK @artursouza

------------------
ANNOUNCEMENT DAY: 02/14/2023
- [x] Update supported versions table in docs @nyemade-uversky
- [x] Merge this quickstarts PR https://github.com/dapr/quickstarts/pull/778
- [x] Release blog @nyemade-uversky 
- [x] Tweet release announcement @msfussell 
- [x] Discord release announcement @artursouza 
- [x] Update versions in the E2E tests in CLI to the latest runtime and dashboard versions @pravinpushkar 
- [x] Merge (NOT SQUASH MERGE/AUTO MERGE) back release-1.10 branch into master for required repos @artursouza 
- [x] Celebrate (everyone)

**Comment by ItalyPaleAle** [comment]
I've checked off the dev container items for dapr/dapr and dapr/components-contrib as I made the required changes and validated nothing else is needed.

For the future, we will not need to make changes to dev containers anymore on releases.

**Comment by shubham1172** [comment]
Please check "Validate Dapr CLI non-slim scenarios on Windows" line item, has been verified with CLI v1.10.0-rc.2

**Comment by mukundansundar** [comment]
A check for the dashboard stable version in k8s was commented out in the E2E last week, since 1.9.6 helm chart still installs only 0.11.0 version of dashboard while the latest stable version of dashboard is 0.11.1. 
The comment in E2E test will be removed once a stable version of both dashboard and dapr/dapr are released.

**Comment by mukundansundar** [comment]
A potential issue in CLI workflow https://github.com/dapr/cli/issues/1225
here only the last step winget PR creation is failing, but the release notification trigger, binaries publish etc are passing.

**Comment by artursouza** [comment]
## Retrospective (in progress)
### What went well
  - Many large features
  - More contributors
  - Release process is clearly defined
  

### What did not go well
  - Remove Temporal in the "last minute"
  - Hotfix right after release
  - Got into endgame without checking longhaul, go-routine leak in ASB since 1.9
  - No alerts from nightly longhaul about memory consumption (all might be done now)
  - Dashboard needs a maintainer and it was added to the release in the last minute due to the `dapr run -f .` feature in CLI
  - Wrong tagging of the hotfix
 
### Action items
 - Validate sidecar size and virt memory increase, adding defined max increase per component - @artursouza
 - Make longhaul better and also not Microsoft specific.
 - Add new E2E test to catch binding problem detected via Zeebe (but is not Zeebe specific).
 - Remove Dashboard from the dapr/dapr's Helm chart - @artursouza
 - Add script to automatically tag based on the desired version to be cut - @artursouza (DONE)
