### ISSUE TITLE
1.9.6 Hotfix Release Checklist

### ISSUE THREAD

**Issue by berndverst** [dapr/dapr#5881]
- [x] Dapr maintainer(s) communicate out the discovery of an issue that requires a hotfix and the reason why to the Discord Maintainers and Release channels. Hotfix is one of categories below:
   - [ ] ~~Security vulnerability~~
   - [ ] ~~Regression that does not have a work around~~
   - [x] Broken mainline scenario that has a missing test case
- [x] Create the v1.9.6 Hotfix release (code changes) and test it
- [ ] ~~Create v1.9.6-rc.1 Tag~~
- [ ] ~~Performance tests passing:~~
- [x] End to End tests passing on Linux and Windows: 
- [x] New test case written to catch future occurrences
- [x] Write release notes [@ItalyPaleAle ]
- [x] Review release notes [@berndverst ]
- [x] Create v1.9.6 Tag [@berndverst ] **Currently blocked due to Docker buildx changes**
- [ ] ~~Backport fixes into master branch~~
- [x] Update the documentation: Latest version & versions in supported releases [@berndverst ]
- [x] Push new tag in installer-bundle repo. [@shivamkm07]
- [x] Announce the hotfix release on Discord Announcements channel [@berndverst ]

**Comment by berndverst** [comment]
Completed.
