### ISSUE TITLE
Workflow 1.11 Tracking Issue

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/dapr#6111]
**Description:**
This is the workflow tracking issue for the large features/improvements planned for the 1.11 release. Full board can be found here: https://github.com/orgs/dapr/projects/61

**1.11 Items:**
- [x] #6045 
- [x] #6043 
- [x] #6070 
- [x] #6042 
- [x] #6039 
- [x] https://github.com/dapr/dotnet-sdk/issues/1027
- [x] https://github.com/dapr/dapr/issues/5911
- [x] https://github.com/dapr/dapr/issues/6073
