### ISSUE TITLE
[Tracking issue] Crypto(graphy) building block

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6147]
This issue tracks the work needed to release the crypto(graphy) building block.

- kit:
  - [X] dapr/kit#38
  - [X] dapr/kit#40
  - [ ] Implementation of `dapr.io/enc/v1` scheme for high-level APIs
- Components-contrib:
  - [X] dapr/components-contrib#2690
  - [X] dapr/components-contrib#2691
  - [X] dapr/components-contrib#2692
  - [ ] dapr/components-contrib#2693
- Runtime:
  - [ ] #6135
  - [ ] #6136
  - [ ] #6137 (likely pushed to 1.12)
  - [ ] High-level APIs
