### ISSUE TITLE
1.10.7 Hotfix Release Checklist

### ISSUE THREAD

**Issue by berndverst** [dapr/dapr#6330]
- [X] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
   - [ ] Security vulnerability
   - [X] Regression that does not have a work around:
     - dapr/components-contrib#2755
     - https://github.com/dapr/dapr/issues/6324
   - [ ] Broken mainline scenario that has a missing test case:
- [x] Create v1.10.7-rc.2 Tag
- [x] Performance tests passing: https://github.com/dapr/dapr/actions/runs/4961139517
- [x] End to End tests passing on Linux and Windows: https://github.com/dapr/dapr/actions/runs/4961146669
- [x] New test case written to catch future occurrences (yes but in contrib certification test - separate PR that is open).  (Including in PRs above)
- [x] Notify users to try RC2
- [x] Update the longhaul tests to use 1.10.7-rc.2
- [x] Write release notes [@berndverst ]: 
- [x] Review release notes [@dapr/maintainers-dapr ]
- [x] Create v1.10.7 Tag [@dapr/maintainers-dapr ]
- [x] Backport fixes into master branch [@dapr/maintainers-dapr ]
- [x] Update the documentation: Latest version & versions in supported releases [@nyemade-uversky ]
- [x] Push new tag in installer-bundle repo. [@artursouza or @shivamkm07]
- [x] Announce the hotfix release on Discord Announcements channel [@nyemade-uversky or @greenie-msft ]

**Comment by mukundansundar** [comment]
installer bundle https://github.com/dapr/installer-bundle/releases/tag/v1.10.7
