### ISSUE TITLE
1.10.8 Patch Release Checklist

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#6511]
- [ ] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
   - [ ] Security vulnerability
   - [x] Regression that does not have a work around:
     - https://github.com/dapr/dapr/pull/6501
     - https://github.com/dapr/dapr/pull/6492
     - https://github.com/dapr/dapr/pull/6431
     - ~https://github.com/dapr/components-contrib/pull/2910~
     - https://github.com/dapr/dapr/issues/6497#issuecomment-1589683252
       - https://github.com/dapr/dapr/pull/6529
     - https://github.com/dapr/dapr/pull/6513
     - https://github.com/dapr/dapr/pull/6554
     - https://github.com/dapr/dapr/issues/6543
       - https://github.com/dapr/dapr/pull/6545
     - https://github.com/dapr/dapr/pull/6561
   - [ ] Broken mainline scenario that has a missing test case:
- [x] Create v1.10.8-rc.1 Tag
- [ ] Performance tests passing: 
- [x] End to End tests passing on Linux and Windows: 
- [ ] New test case written to catch future occurrences 
- [x] Notify users to try RC1
- [ ] Update the longhaul tests to use 1.10.8-rc.21
- [x] Write release notes : 
- [x] Review release notes [@dapr/maintainers-dapr ]
- [x] Create v1.10.8 Tag [@dapr/maintainers-dapr ]
- [ ] Backport fixes into master branch [@dapr/maintainers-dapr ]
- [ ] Update the documentation: Latest version & versions in supported releases
- [ ] Push new tag in installer-bundle repo.
- [x] Announce the hotfix release on Discord Announcements channel

**Comment by ItalyPaleAle** [comment]
As discussed this morning, dapr/components-contrib#2910 is not going to be included as a hotfix for 1.10 nor 1.11. When we have a backwards-compatible fix, we'll include it in the next major release.

**Comment by berndverst** [comment]
Please also include the fix for https://github.com/dapr/components-contrib/issues/2901

Working on it right now.

**Comment by JoshVanL** [comment]
Release: https://github.com/dapr/dapr/releases/tag/v1.10.8

**Comment by JoshVanL** [comment]
Done.
