### ISSUE TITLE
1.11.1 Patch Release Checklist

### ISSUE THREAD

**Issue by berndverst** [dapr/dapr#6531]
- [x] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
   - [ ] Security vulnerability
   - [x] Regression that does not have a work around:
     - https://github.com/dapr/dapr/issues/6543
     - https://github.com/dapr/dapr/issues/6517
     - https://github.com/dapr/dapr/issues/6497
     - https://github.com/dapr/components-contrib/issues/2913
     - https://github.com/dapr/components-contrib/pull/2920
     - https://github.com/dapr/components-contrib/issues/2901
       - https://github.com/dapr/dapr/pull/6559
   - [ ] Broken mainline scenario that has a missing test case:
- [x] Create v1.11.1-rc.1 Tag
- [ ] Performance tests passing: 
- [x] End to End tests passing on Linux and Windows: 
- [ ] New test case written to catch future occurrences 
- [x] Notify users to try RC1
- [x] Update the longhaul tests to use v1.11.1-rc.1
- [x] Write release notes : 
- [x] Review release notes [@dapr/maintainers-dapr ]
- [x] Create v1.11.1 Tag [@dapr/maintainers-dapr ]
- [ ] Backport fixes into master branch [@dapr/maintainers-dapr ]
- [ ] Update the documentation: Latest version & versions in supported releases
- [ ] Push new tag in installer-bundle repo.
- [x] Announce the patch release on Discord Announcements channel

**Comment by berndverst** [comment]
Updated the issue to include https://github.com/dapr/dapr/pull/6559 which fixes the Azure Service Bus Queues issue listed above.

**Comment by JoshVanL** [comment]
Release: https://github.com/dapr/dapr/releases/tag/v1.10.8

**Comment by JoshVanL** [comment]
Done.
