### ISSUE TITLE
[Error Handling/Codes] v1.13 Tracking issue

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#6567]
Related to proposal https://github.com/dapr/proposals/blob/main/0009-BCIRS-error-handling-codes.md

- [ ] https://github.com/dapr/dapr/issues/6470
- [ ] https://github.com/dapr/dapr/issues/6471
- [ ] https://github.com/dapr/dapr/issues/6472
- [ ] https://github.com/dapr/dapr/issues/6473
