### ISSUE TITLE
[Tracking] 1.11.2 security & patch release

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6662]
- [x] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
   - Security vulnerability
      - CVE-2023-37475: dapr/components-contrib#2994
   -  Regression that does not have a work around:
       - #6558
         - PR: #6661
       - #6618
         - PR: #6661
       - #6659 
         - PR: #6661
   - Broken mainline scenario that has a missing test case:
- [x] Create v1.11.2-rc.3 Tag
- [x] Performance tests passing: https://github.com/dapr/dapr/actions/runs/5603924018
- [x] End to End tests passing on Linux and Windows: https://github.com/dapr/dapr/actions/runs/5603912593
- [x] New test case written to catch future occurrences 
- [ ] ~Notify users to try RC3~
- [x] Update the longhaul tests to use v1.11.2-rc.2
- [x] Write release notes
  - Included in PRs
- [x] Review release notes [@dapr/maintainers-dapr ]
- [ ] Create v1.11.2 Tag [@dapr/maintainers-dapr ]
- [ ] Backport fixes into master branch [@dapr/maintainers-dapr ]
- [ ] Update the documentation: Latest version & versions in supported releases
- [ ] Push new tag in installer-bundle repo.
- [ ] Announce the patch release on Discord Announcements channel

**Comment by ItalyPaleAle** [comment]
Released
