### ISSUE TITLE
[Tracking] 1.10.9 security release

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6685]
- [x] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
   - Security vulnerability
      - CVE-2023-37475
         - dapr/components-contrib#2995
         - #6686
   -  Regression that does not have a work around:
   - Broken mainline scenario that has a missing test case:
- ~~Create v1.10.9-rc.1 Tag~~
- ~~Performance tests passing~~
- [x] End to End tests passing on Linux and ~Windows~: https://github.com/dapr/dapr/actions/runs/5603911925
- ~~New test case written to catch future occurrences~~
- ~~Notify users to try RC1~~
- ~~Update the longhaul tests to use v1.10.9-rc.1~~
- [x] Write release notes
- [x] Review release notes [@dapr/maintainers-dapr ]
- [ ] Create v1.10.9 Tag [@dapr/maintainers-dapr ]
- [ ] Backport fixes into master branch [@dapr/maintainers-dapr ]
- [ ] Update the documentation: Latest version & versions in supported releases
- [ ] Push new tag in installer-bundle repo.
- [ ] Announce the patch release on Discord Announcements channel

**Comment by ItalyPaleAle** [comment]
Released
