### ISSUE TITLE
1.11.3 Patch Release checklist

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#6862]
- [x] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
   - [ ] Security vulnerability
   - [x] Regression that does not have a work around:
     - https://github.com/dapr/dapr/issues/6655
     - https://github.com/dapr/dapr/pull/6863
   - [ ] Broken mainline scenario that has a missing test case:
- [x] Create v1.11.3-rc.1 Tag
- [x] Performance tests passing: 
- [x] End to End tests passing on Linux and Windows: 
- [ ] New test case written to catch future occurrences 
- [x] Notify users to try RC1
- [ ] Update the longhaul tests to use v1.11.3-rc.1
- [x] Write release notes : 
- [x] Review release notes [@dapr/maintainers-dapr ]
- [x] Create v1.11.3 Tag [@dapr/maintainers-dapr ]
- [x] Backport fixes into master branch [@dapr/maintainers-dapr ]
- [x] Update the documentation: Latest version & versions in supported releases
- [x] Push new tag in installer-bundle repo.
- [x] Announce the patch release on Discord Announcements channel

**Comment by mukundansundar** [comment]
E2E passing on linux consistently .... 
On Windows ... They are consistently flaky ... but all tests seem to have passed at least once in different runs.

**Comment by mukundansundar** [comment]
Completed
