### ISSUE TITLE
v1.12 Endgame

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#6899]
## Release team
Release lead: @mukundansundar 
Release lead shadow(s): @JoshVanL 
Perf test lead: @yaron2 
Long haul test: @tmacam @halspang 
Build manager:

Read about the [Dapr release lifecycle](https://github.com/dapr/community/blob/master/release-process.md)

## Milestone dates
Code freeze: 9/5/2023
Endgame starts: 9/7/2023
Endgame ends: 10/11/2023
1.12.0 release: 10/11/2023 - 10/12/2023

Release Tasks:

------------------
- [x] Code freeze at 09/05/2023
- [x] All P0 issues below are resolved PRIOR to code freeze:
  - [x] https://github.com/dapr/dapr/issues/6893
  - [x] https://github.com/dapr/dapr/pull/6911 @shivamkm07 
  - [x] https://github.com/dapr/dapr/issues/6503 @DeepanshuA @ItalyPaleAle 
  - [x] https://github.com/dapr/dapr/issues/6339 @artursouza 
  - [x] https://github.com/dapr/dapr/issues/6905
  - [x] https://github.com/dapr/cli/issues/1341 @JoshVanL
  - [x] https://github.com/dapr/dapr/issues/6949 @JoshVanL 
  - [x] https://github.com/dapr/dapr/issues/6940 @ItalyPaleAle 
  - [x] https://github.com/dapr/dapr/issues/6964 @ItalyPaleAle @DeepanshuA @tmacam 
  - [x] https://github.com/dapr/dapr/pull/6973
  - [x] https://github.com/dapr/dapr/pull/6972
  - [x] https://github.com/dapr/dapr/pull/6977
  - [x] https://github.com/dapr/dapr/issues/6997
  - [x] https://github.com/dapr/components-contrib/pull/3169
  - [x] https://github.com/dapr/dapr/pull/6968
  - [x] https://github.com/dapr/dapr/issues/7012 @halspang @yaron2 @ItalyPaleAle 
- [x] Must haves for 1.12
  - [x] https://github.com/dapr/java-sdk/issues/932 @artursouza 
  - [x] https://github.com/dapr/cli/issues/1351 @mukundansundar 
  - [x] https://github.com/dapr/dapr/pull/6895
  - [x] https://github.com/dapr/dapr/pull/6867
  - [x] https://github.com/dapr/java-sdk/pull/880
  - [x] https://github.com/dapr/dotnet-sdk/pull/1141
  - [x] https://github.com/dapr/java-sdk/pull/916 @skyao 
  - [x] https://github.com/dapr/python-sdk/issues/594 @DeepanshuA 
  - [x] https://github.com/dapr/js-sdk/issues/520 Elena
  - [x] https://github.com/dapr/dapr/pull/6761
  - [x] https://github.com/dapr/cli/pull/1348 @pravinpushkar 
- [x] Check all new components are registered in dapr/dapr @mukundansundar 
- [x]  E2E, certification and perf tests are passing @mukundansundar 
  - [x] E2E: https://github.com/dapr/dapr/actions/runs/6178835418 Tests are flaky but this is test run for the commit for 1.12-RC.1
  - [x] Perf: Perf tests consistently failing. P0 @yaron2 
- [x] Create release-1.12 branch and cut RC 1.12.0-rc.1 for component-contrib @berndverst 
- [x] Update dapr/component-contrib pkg to 1.12.0-rc.1 in dapr/dapr master branch @berndverst 
- [x] Create release-1.12 branch for Dapr runtime @artursouza 
- [x] ~Verify helm chart and c~Cut the 1.12.0-rc.1 release for Dapr runtime @artursouza 
- [x] Create release-1.12 branch for CLI @mukundansundar 
- [x] Update dapr/dapr pkg to 1.12.0-rc.2 in dapr/cli release-1.12 branch @JoshVanL 
- [x] Cut the 1.12.0-rc.1 release for CLI @mukundansundar 
- [x] Trigger GitHub actions in dapr/homebrew-tap (GitHub disables Actions after 1mo without commits) @mukundansundar 
- [x] Notify users about dapr/dapr 1.12.0-rc.1 via Discord @mukundansundar 
- [x] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. @pravinpushkar 
- [x] Create RC for installer-bundle @mukundansundar 
- [x] Validate RC for installer bundle @shivamkm07 
- [x] Update proto and cut the rc release for Java SDK   @artursouza 
- [x] Update proto for Python SDK @berndverst 
- [x] Update proto for Go SDK @yaron2 
- [x] Update proto and cut the rc release for dotnet SDK  @halspang @johnewart 
- [x] Update proto cpp SDK  - Elena
- [x] Update proto for rust SDK - Elena
- [x] Cut the rc release for Dashboard @artursouza
- [x] Update longhaul tests with RC for runtime and dotnet SDK @tmacam 
- [x] Update quickstarts/tutorials automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS. - @cicoyle 
- [x] Create PR for quickstarts to point to RC SDKs/Dev package? if it is available - @paulyuk 
- [x] Test and validate tutorials in Linux ARM64 k8s and self-hosted - @yaron2 
- [x] Test and validate tutorials in Windows - @rabollin 
- [x] Validate Dapr CLI non-slim scenarios on Windows - @shubham1172 
- [x] Validate Multi app run K8s on Windows - @shivamkm07  
- [x] Validate longhaul metrics @tmacam 
- [x] Test and validate the .NET SDK - run through samples @halspang 
- [x] Test and validate the Java SDK - run through samples @artursouza 
- [x] Test and validate the Python SDK - run through samples @berndverst 
- [x] Test and validate the Go SDK - run through samples @yaron2 
- [x] Test and validate Dashboard, local mode and kubernetes hosted @cicoyle  
- [x] Update certification tests in components-contrib release branch (prior to merge back into master) to use the RC (and Go SDK RC/release if possible). @berndverst @yaron2 
- [x] Confirm with maintainers that each repo has milestone set for all relevant issues & PRs, then generate release notes
  - [x] CLI - @mukundansundar @yaron2 
  - [x] runtime - @artursouza @yaron2 @mukundansundar 
  - [x] components-contrib - @artursouza @yaron2 @berndverst @DeepanshuA 
  - [x] .NET SDK - @halspang 
  - [x] Java SDK - @artursouza 
  - [x] JS SDK - @shubham1172 
  - [x] Python SDK - @berndverst 
  - [x] Go SDK - @yaron2 
  - [x] Check all milestones for each repo above are up to date before cutting the release notes. @artursouza
- [x] Validate FOSSA on each repo 
  - [x] CLI - @mukundansundar @yaron2 
  - [x] runtime - @artursouza @yaron2 @mukundansundar 
  - [x] components-contrib @dapr/maintainers-components-contrib 
  - [x] .NET SDK - @halspang 
  - [x] Java SDK - @artursouza 
  - [x] ~JS SDK~ - @shubham1172 
  - [x] Python SDK - @berndverst 
  - [x] Go SDK - @yaron2 
- [x] Edit and complete release-notes on HackMD (everyone) @mukundansundar @ItalyPaleAle 
- [x] Verify 1.12 documentation - @dapr/maintainers-docs 

ETA for all above: ~ 10/06/2023

------------------
RELEASE DAY: 10/11/2023

- [x] Release Dashboard @artursouza, update dapr/dapr's helm chart to remove RC suffix
- [x] Validate breaking changes section in release notes @mukundansundar 
- [x] Merge release notes into release branch @mukundansundar 
- [x] Cut tag for components-contrib @artursouza 
- [x] Release Dapr 1.12 @artursouza 
- [x] Release CLI 1.12 @mukundansundar 
- [x] Release Installer Bundle 1.12 @mukundansundar 
- [x] Create blog post @paulyuk 
- [x] Release cpp-sdk @yaron2 
- [x] Release js-sdk @shubham1172 @XavierGeerinck 
- [x] Release go-sdk @yaron2 
- [x] Release java-sdk @artursouza 
- [x] Release python-sdk @berndverst 
- [x] Release rust-sdk @yaron2 
- [x] Release dotnet-sdk and release nuget packages @halspang 
- [x] Create release-1.12 branch for quickstarts, update version tag in the images, create v1.12.0 tag @paulyuk 
- [x] Create components-contrib release from Tag. Copy components release notes section into the description of the release. @artursouza  
- [x] Validate DevContainers in following repos
  - [x] dapr/dapr @mukundansundar 
  - [x] dapr/components-contrib @mukundansundar 
  - [x] dapr/cli @mukundansundar 
- [x] Update certification tests in components-contrib release branch (prior to merge back into master) to use latest runtime and Go SDK release. @berndverst 
- [x] Generate new Java docs based on the release version of the Java SDK @artursouza 

------------------
ANNOUNCEMENT DAY: 10/12/2023
- [x] Update supported versions table in docs @dapr/maintainers-docs
- [x] Release blog @dapr/maintainers-blog 
- [x] Post release announcement in 'X' @dapr/maintainers-blog 
- [x] Discord release announcement @dapr/maintainers-dapr 
- [x] Update versions in the E2E tests in CLI to the latest runtime and dashboard versions @shivamkm07  @mukundansundar 
- [x] Merge (NOT SQUASH MERGE/AUTO MERGE) back release-1.12 branch into master for required repos @mukundansundar 
- [x] Celebrate (everyone)

**Comment by shubham1172** [comment]
FYI Dapr CLI non-slim scenarios have been validated on Windows (test plan: https://github.com/dapr/cli/issues/1078).

**Comment by rabollin** [comment]
Test and validate tutorials in Windows = done (no issues)

**Comment by cicoyle** [comment]
quickstarts/tutorials automated validation and check it works - MacOS = done (no issues)

**Comment by mukundansundar** [comment]
all tasks complete for 1.12.
