### ISSUE TITLE
v1.13 Release Planning

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7093]
## Release team
Release lead: @JoshVanL  
Release lead shadow(s): @mikeee  
Perf test lead:  @yaron2 
Longhaul test: TODO
Build manager: TODO

Read about the [Dapr release lifecycle](https://github.com/dapr/community/blob/master/release-process.md)

## Milestone dates
Feature definition starts:  2023-10-24
Feature definition ends: 2023-11-07
Feature freeze: 2023-12-19
Code freeze (Endgame starts ~2 weeks stabilization): 2024-01-16
RC Release day: ~2024-01-30
Announcement day: 2024-02-15 < - Docs, Samples and Runtime, CLI, Release notes

##  Priorities for this release

- [x] [P0] New name resolver https://github.com/dapr/dapr/issues/3256
- [ ] [P0] Presence of AppChannelAllowInsecureTLS feature flag https://github.com/dapr/dapr/issues/7149
- [x] [P0] Go 1.21 https://github.com/dapr/dapr/issues/7228
- [ ] [P0] Hot reloading (Components) https://github.com/dapr/dapr/issues/1172 
  - [ ] [P1] Hot reloading (Resiliency) https://github.com/dapr/dapr/issues/5435
  - [ ] [P1] Hot reloading (Subscriptions) https://github.com/dapr/dapr/issues/7139 
- [ ] [P0] Identity improvements https://github.com/dapr/dapr/issues/5756
- [x] [P0] Metrics cardinality https://github.com/dapr/dapr/pull/6919 needs docs
- [ ] [P0] Distributed scheduler planning+beginning implementation https://github.com/dapr/proposals/pull/44
- [ ] [P0] Workflow as stable {Phase 1} https://github.com/dapr/dapr/issues/7156
- [ ] [*P0 needs owner*] Bulk pubsub as stable https://github.com/dapr/dapr/issues/7157
- [ ] [P1 start work] Component Resiliency (TODO) @berndverst 
- [ ] [P1] Auto-configure middleware pipelines https://github.com/dapr/dapr/issues/6660
- [ ] [P1] Reduce the flakyness in E2E tests https://github.com/dapr/dapr/issues/7128
- [ ] [P1] Error code standardization https://github.com/dapr/dapr/issues/6068
- [ ] [P1] Trust distribution https://github.com/dapr/proposals/pull/42 & CA rotation https://github.com/dapr/dapr/issues/5958
- [ ] [P1 needs owner] Local developer experience https://github.com/dapr/cli/issues/1354
- [ ] Not service invocation for non Dapr endpoints (TODO) @yaron2  ~
- [ ] [P1] Actor state TTL https://github.com/dapr/dapr/issues/5899
- [ ] [P1] Implement DAPR_API_TOKEN across SDKs 
  - [ ] https://github.com/dapr/rust-sdk/issues/111
  - [ ] https://github.com/dapr/cpp-sdk/issues/59
  - [x] https://github.com/dapr/js-sdk/issues/547 
- [ ] [P1] Actor Log and metrics improvements (Delete Actor support, Diagnostics Logs in actor State store logs)
  - [ ] https://github.com/dapr/dapr/issues/6992
  - [ ] https://github.com/dapr/dapr/issues/6993
- [ ] [P1 needs owner & proposal] Dapr SDKs constructing a Service Invocation client with resiliency, TLS etc. (TODO) @mikeee 
- [ ] [P1 EPIC] Contributor docs improvements https://github.com/dapr/dapr/issues/5885

## Not prioritized 
- Migrating redis to SQLite as default state store

## Moved to v1.14
- [ ] [P1 needs owner] Scoping Dapr to run in a single namespace natively https://github.com/dapr/dapr/issues/6611
- [ ] [P1 needs owner] GRPC middleware https://github.com/dapr/dapr/issues/4153
- [ ] [P2 needs owner] Change logger to slog, implemented by zap or similar. https://github.com/dapr/dapr/issues/6129 (needs issue in dapr/kit).

## Repo milestones
Dapr - https://github.com/dapr/dapr/milestone/20
CLI - https://github.com/dapr/cli/milestone/14
Docs - https://github.com/dapr/docs/milestone/16
Components-contrib - https://github.com/dapr/components-contrib/milestone/14
Java-SDK - https://github.com/dapr/java-sdk/milestone/11
Python-SDK - https://github.com/dapr/python-sdk/milestone/13
Dotnet-SDK - https://github.com/dapr/dotnet-sdk/milestone/18
Js-SDK - https://github.com/dapr/js-sdk/milestone/14
Go-SDK - https://github.com/dapr/go-sdk/milestone/10
Dashboard: not releasing this time
Quickstarts (aka Tutorials) - https://github.com/dapr/quickstarts/milestone/9

**Comment by robi-y** [comment]
What is the plan for #4541 please?

**Comment by JoshVanL** [comment]
Endgame issue: https://github.com/dapr/dapr/issues/7410

**Comment by yaron2** [comment]
> What is the plan for #4541 please?

Commented on the issue

**Comment by Admiralkheir** [comment]
According to the log provided by dapr runtime in 1.12.4, NATS streaming will be removed with version 1.13, but we could not fully switch to JetStream due to parallel processing and dependency on this component throughout our applications. What is the plan for [3115](https://github.com/dapr/components-contrib/issues/3115)

**Comment by yaron2** [comment]
> According to the log provided by dapr runtime in 1.12.4, NATS streaming will be removed with version 1.13, but we could not fully switch to JetStream due to parallel processing and dependency on this component throughout our applications. What is the plan for [3115](https://github.com/dapr/components-contrib/issues/3115)? ty

Responded on https://github.com/dapr/components-contrib/issues/3115

**Comment by JoshVanL** [comment]
Dapr v1.13 has been released https://github.com/dapr/dapr/releases/v1.13.0
