### ISSUE TITLE
1.12.1 Patch Release Checklist

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7124]
- [ ] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
   - [ ] Security vulnerability
     - https://github.com/dapr/dapr/pull/7116
   - [ ] Regression that does not have a work around:
     - https://github.com/dapr/components-contrib/pull/3199
     - https://github.com/dapr/dapr/pull/7066
     - https://github.com/dapr/dapr/pull/7082
     - https://github.com/dapr/dapr/pull/7094
     - https://github.com/dapr/components-contrib/issues/3204
     - https://github.com/dapr/dapr/pull/7172
   - [ ] Broken mainline scenario that has a missing test case:
- [ ] Create v1.12.1-rc.2 Tag
- [ ] Performance tests passing: 
- [ ] End to End tests passing on Linux and Windows: 
- [ ] New test case written to catch future occurrences 
- [ ] Notify users to try RC1
- [ ] Update the longhaul tests to use v1.12.1-rc.2
- [ ] Write release notes :  https://github.com/dapr/dapr/pull/7150
- [ ] Review release notes [@dapr/maintainers-dapr ]
- [ ] Create v1.12.1 Tag [@dapr/maintainers-dapr ]
- [ ] Backport fixes into master branch [@dapr/maintainers-dapr ]
- [ ] Update the documentation: Latest version & versions in supported releases
- [ ] Push new tag in installer-bundle repo.
- [ ] Announce the patch release on Discord Announcements channel

**Comment by artursouza** [comment]
Pending the Consul fix.
