### ISSUE TITLE
1.11.5 Patch Release Checklist

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7125]
- [ ] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
   - [ ] Security vulnerability
     - https://github.com/dapr/dapr/pull/7117
   - [ ] Regression that does not have a work around:
     - https://github.com/dapr/dapr/pull/7002
     - https://github.com/dapr/dapr/pull/7018
     - https://github.com/dapr/dapr/pull/7057
     - https://github.com/dapr/dapr/pull/7068
   - [ ] Broken mainline scenario that has a missing test case:
- [ ] Create v1.11.5-rc.3 Tag
- [ ] Performance tests passing: 
- [ ] End to End tests passing on Linux and Windows: 
- [ ] New test case written to catch future occurrences 
- [ ] Notify users to try RC1
- [ ] Update the longhaul tests to use v1.11.5-rc.3
- [ ] Write release notes :  https://github.com/dapr/dapr/pull/7144
- [ ] Review release notes [@dapr/maintainers-dapr ]
- [ ] Create v1.11.5 Tag [@dapr/maintainers-dapr ]
- [ ] Backport fixes into master branch [@dapr/maintainers-dapr ]
- [ ] Update the documentation: Latest version & versions in supported releases
- [ ] Push new tag in installer-bundle repo.
- [ ] Announce the patch release on Discord Announcements channel

**Comment by JoshVanL** [comment]
v1.11.5 released https://github.com/dapr/dapr/releases/tag/v1.11.5
