### ISSUE TITLE
1.10.10 Patch Release Checklist

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7126]
- [ ] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
   - [ ] Security vulnerability
     - https://github.com/dapr/dapr/pull/7118
     - https://github.com/dapr/dapr/pull/7091
   - [ ] Regression that does not have a work around:
   - [ ] Broken mainline scenario that has a missing test case:
- [ ] Create v1.10.10-rc.1 Tag
- [ ] Performance tests passing: 
- [ ] End to End tests passing on Linux and Windows: 
- [ ] New test case written to catch future occurrences 
- [ ] Notify users to try RC1
- [ ] Update the longhaul tests to use v1.10.10-rc.1
- [ ] Write release notes : 
- [ ] Review release notes [@dapr/maintainers-dapr ]
- [ ] Create v1.10.10 Tag [@dapr/maintainers-dapr ]
- [ ] Backport fixes into master branch [@dapr/maintainers-dapr ]
- [ ] Update the documentation: Latest version & versions in supported releases
- [ ] Push new tag in installer-bundle repo.
- [ ] Announce the patch release on Discord Announcements channel

**Comment by shivamkm07** [comment]
This PR needs to be included as well in 1.10 patch release: https://github.com/dapr/dapr/pull/7091

**Comment by JoshVanL** [comment]
Released https://github.com/dapr/dapr/releases/tag/v1.10.10
