### ISSUE TITLE
Workflow to Stable - Phase1

### ISSUE THREAD

**Issue by rabollin** [dapr/dapr#7156]
This is a tracking issue to capture the set of issues and enhancements that we must address driving the Workflow to a stable release.  We will be implementing the stable criteria guidelines in phases and the Phase1 covering below issues or enhancements will be addressed in 1.13

WF Engine:
- [x] https://github.com/dapr/dapr/issues/7089  (Decouple the Workflow backend and make it as configurable component)
- [x] https://github.com/dapr/dapr/issues/7065
- [x] https://github.com/dapr/dapr/pull/7231
- [x] https://github.com/dapr/dapr/issues/7109
-Workflow Bugs: 
   - [x] https://github.com/dapr/dapr/issues/7101 (Make it easier for developers to reuse existing workflow ID)
   - [x] https://github.com/dapr/dapr/issues/6393
   - [x] JAVA SDK – Workflow cannot be scheduled at specific date.time unlike other SDKs: https://github.com/dapr/java-sdk/issues/943
- SDKs:
   - [x] JavaScript: https://github.com/dapr/js-sdk/issues/463; https://github.com/dapr/js-sdk/issues/545
   - [x] Go: https://github.com/dapr/go-sdk/issues/379 
- SDK improvements:
   - [x] .NET logs enhancements: https://github.com/dapr/dotnet-sdk/issues/1170
   - [x] Python SDK logs enhancements:  https://github.com/dapr/python-sdk/issues/626
   - [x] Java SDK logs enhancements: https://github.com/dapr/java-sdk/issues/946
   - [x] Python Programming model enhancements: https://github.com/dapr/python-sdk/issues/635

**Comment by JoshVanL** [comment]
@rabollin Please can we include adding integration tests as a requirement for the workflow API becoming stable. We currently don't so have limited test coverage.

**Comment by rabollin** [comment]
> @rabollin Please can we include adding integration tests as a requirement for the workflow API becoming stable. We currently don't so have limited test coverage.

Yes, Integration tests will be added as relevant.

**Comment by mukundansundar** [comment]
This issue can be closed once the Go SDK PRs are merged.

**Comment by JoshVanL** [comment]
This is done
