### ISSUE TITLE
Bulk PubSub as Stable

### ISSUE THREAD

**Issue by DeepanshuA** [dapr/dapr#7157]
## In what area(s)?

> /area runtime

## What is it about

This issue tracks all the remaining work items to make Bulk PubSub as Stable:

- [ ] Comprehensive E2E Tests i.e. Inclusion of Negative cases
                  - [ ]  https://github.com/dapr/dapr/issues/5923
                  - [ ] https://github.com/dapr/dapr/issues/5995
- [ ] SDK Spec for Bulk Subscribe (https://github.com/dapr/sig-sdk-spec/issues/24)
- [ ] Support in Python SDK for Bulk Publish and Bulk Subscribe (https://github.com/dapr/python-sdk/issues/464)
- [ ] Support in GO SDK for Bulk Subscribe (https://github.com/dapr/go-sdk/issues/423)
- [ ] Quickstarts for Bulk Publish and Bulk Subscribe (Java, JS, .NET, Python, Go)
- [ ] Certification tests for implementations
                  - [ ]  https://github.com/dapr/components-contrib/issues/2612

**Comment by JoshVanL** [comment]
Moving to milestone v1.14 as not enough time for v1.13

**Comment by mikeee** [comment]
@DeepanshuA is this something that is being actively tracked and likely to be delivered/implemented for 1.14? (28th May 2024 feature implementation deadline)

**Comment by mcupito** [comment]
Hi team, do we think this will be shipped as part of 1.14? Thank you!

**Comment by yaron2** [comment]
> Hi team, do we think this will be shipped as part of 1.14? Thank you!

Unfortunately not, but it's a high priority item for 1.15
