### ISSUE TITLE
Tracking: SDKs - Service Invocation Clients implementing resiliency and TLS

### ISSUE THREAD

**Issue by mikeee** [dapr/dapr#7158]
This is a tracking issue for the supported Dapr SDKs with regards to their service invocation clients implementing resiliency and tls.

- [ ] [.NET](https://github.com/dapr/dotnet-sdk/)
  - [ ] Resiliency - Issue/PR: (TODO)
  - [ ] TLS - Issue/PR: (TODO)
- [ ] [Python](https://github.com/dapr/python-sdk/)
  - [ ] Resiliency - Issue/PR: (TODO)
  - [ ] TLS - Issue/PR: (TODO)
- [ ] [Java](https://github.com/dapr/java-sdk/)
  - [ ] Resiliency - Issue/PR: (TODO)
  - [ ] TLS - Issue/PR: (TODO)
- [ ] [Go](https://github.com/dapr/go-sdk/)
  - [ ] Resiliency - Issue/PR: (TODO)
  - [ ] TLS - Issue/PR: (TODO)
- [ ] [PHP](https://github.com/dapr/php-sdk/)
  - [ ] Resiliency - Issue/PR: (TODO)
  - [ ] TLS - Issue/PR: (TODO)
- [ ] [JavaScript](https://github.com/dapr/js-sdk/)
  - [ ] Resiliency - Issue/PR: (TODO)
  - [ ] TLS - Issue/PR: (TODO)

Dev:
- [ ] [C++](https://github.com/dapr/cpp-sdk/)
  - [ ] Resiliency - Issue/PR: (TODO)
  - [ ] TLS - Issue/PR: (TODO)
- [ ] [Rust](https://github.com/dapr/rust-sdk/)
  - [ ] Resiliency - Issue/PR: (TODO)
  - [ ] TLS - Issue/PR: (TODO)

cc @JoshVanL - v1.13
