### ISSUE TITLE
1.12.4 Patch Release Checklist

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7317]
- [x] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
  - [x] Security vulnerability
    - <>
  - [x]  Regression that does not have a work around:
    - https://github.com/dapr/dapr/pull/7333
    - https://github.com/dapr/dapr/pull/7349
   - [x] Broken mainline scenario that has a missing test case:
 - [x] Create Tag
      - [ ] v1.12.4-rc.1
 - [ ] Performance tests passing
- [ ]  End to End tests passing on Linux and Windows:
- [ ]  New test case written to catch future occurrences
- [ ]  Notify users to try RC (Announce on Discord Announcements channel)
     - [ ] v1.12.4-rc.1 
- [ ]  Update the longhaul tests to use RC
     - [ ] <>
- [ ]  Write release notes : 
- [ ]  Review release notes [@dapr/maintainers-dapr ]
- [ ]  Create v1.12.3 Tag [@dapr/maintainers-dapr ]
- [ ]  Backport fixes into master branch [@dapr/maintainers-dapr ]
- [ ]  Update the documentation: Latest version & versions in supported releases
- [ ]  Push new tag in installer-bundle repo.
- [ ]  Announce the patch release on Discord Announcements channel
