### ISSUE TITLE
v1.14 Release Planning

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#7605]
[Release Tracking Board](https://github.com/orgs/dapr/projects/80)

Release lead: @mikeee 
Release lead shadow(s): -
Perf test lead: @cicoyle 
Longhaul test: @elena-kolevska 
Build manager: @JoshVanL 

Read about the [Dapr release lifecycle](https://github.com/dapr/community/blob/master/release-process.md)

## Milestone dates

- [x] Feature definition starts: 12th March 2024 (12/03/2024)
- [x] Feature definition ends: 26th March 2024 (26/03/2024)
- [x] Feature freeze: ~~14th May 2024~~ -> 28th May 2024
- [x] Code freeze (Endgame starts ~2 weeks stabilization):  ~~28th May 2024~~ -> ~~11th June 2024~~ -> 25th June 2024
- [x] RC Release day: ~~28th May 2024~~ -> ~~11th June 2024~~ -> ~~25th June 2024~~ -> 03rd July 2024
- [x] Release day: ~~11th June 2024~~ -> ~~9th July 2024~~ -> 13th August 2024
- [ ] Announcement day: ~~10th July 2024~~ -> 14th August 2024 < - Docs, Samples and Runtime, CLI, Release notes

## Priorities for this release

- [x] [P0] Longhauls/tests: azurecr non-existent - https://github.com/dapr/test-infra/issues/225
- [x] [P0] Distributed Scheduler Implementation #7246 @cicoyle 
  - [x] cli changes https://github.com/dapr/cli/pull/1405
  - [x] go-sdk implementation https://github.com/dapr/go-sdk/issues/561 @mikeee 
- [x] [P0] Pubsub bidirectional streams [Proposal #52](https://github.com/dapr/proposals/pull/52) @JoshVanL 
  - [x] API -> health/z checks -> split subscriptions into new structures 
  - [x] Go SDK implementation https://github.com/dapr/go-sdk/pull/578
  - [x] #814 @JoshVanL
- [x] [P0] Opencensus / Open telemetry [dapr#7703](https://github.com/dapr/dapr/issues/7703)
- [x] [P1] Finish standardization of env vars java-sdk
  - [x] java-sdk [java-sdk#1028](https://github.com/dapr/java-sdk/issues/1028) @artursouza 
- [x] [P0] Namespaced actors #3786 @elena-kolevska  - https://github.com/dapr/dapr/pull/7745
- [x] [P0] go1.22 upgrade for runtime https://github.com/dapr/dapr/pull/7713
  - [x] components-contrib https://github.com/dapr/components-contrib/pull/3372
    - consider deprecation of binding- cloudwego/kitex
- [x] [P0] Metrics - low cardinality improvement [proposal#58](https://github.com/dapr/proposals/pull/58)
### PRs - Open to Review:

- [x] Healthz Overhaul - https://github.com/dapr/dapr/pull/7518
- [x] Distributed Scheduler - https://github.com/dapr/dapr/pull/7768
- [x] Distributed Scheduler (CLI) - https://github.com/dapr/cli/pull/1405
- [x] Distributed Scheduler (Go-SDK) - https://github.com/dapr/go-sdk/pull/562
- [x] OpenCensus -> OpenTelemetry - https://github.com/dapr/dapr/pull/7735
- [x] Update dependencies - https://github.com/dapr/dapr/pull/7681

## Not prioritized / Non-blocking

- [x] [P1] Workflow memory leak? #7777 @mikeee 
- [x] [P1] Missing DAPR_APP_TOKEN from requests originating from the sidecar #7774 
- [ ] [P1] Finish standardization of env vars dotnet-sdk/rust-sdk
  - [ ] dotnet-sdk [dotnet-sdk#1254](https://github.com/dapr/dotnet-sdk/issues/1254) @artursouza 
  - [ ] rust-sdk [rust-sdk#150](https://github.com/dapr/rust-sdk/issues/150) @mikeee 
  - [ ] Actor state TTLs #5899 
- [ ] [P1] Components init/status health reporting [Proposal #54](https://github.com/dapr/proposals/pull/54) @JoshVanL 
- [ ] Component resiliency? [components-contrib#1863](https://github.com/dapr/components-contrib/issues/1863)
- [ ] Workflow to phase 2 -> issue to be created
- [ ] Bulk-pubsub #5567  @mukundansundar 
- [ ] [P1] Distributed lock to stable [Proposal #43](https://github.com/dapr/proposals/pull/43)
- [ ] [P1] x509 auth for components [Proposal #51](https://github.com/dapr/proposals/pull/51)
- [ ] [P1] Auto-configure middleware pipelines via priority and pipeline type properties #6660 @ItalyPaleAle 
- [x] [P1] Support for Azure Cache for Redis - EntraID auth method (All Redis components) [components-contrib#3088](https://github.com/dapr/components-contrib/issues/3088) @berndverst 
- [ ] [P1] Watch and operate on a particular namespace rather than all namespaces #6611 @yaron2 

[Release Tracking Board](https://github.com/orgs/dapr/projects/80)

## Repo milestones

Dapr - https://github.com/dapr/dapr/milestone/21
CLI - https://github.com/dapr/cli/milestone/15
Docs - https://github.com/dapr/docs/milestone/17
Components-contrib - https://github.com/dapr/components-contrib/milestone/15
Java-SDK - https://github.com/dapr/java-sdk/milestone/12
Python-SDK - https://github.com/dapr/python-sdk/milestone/14
Dotnet-SDK - https://github.com/dapr/dotnet-sdk/milestone/19
Js-SDK - https://github.com/dapr/js-sdk/milestone/15 
Go-SDK - https://github.com/dapr/go-sdk/milestone/11
Rust-SDK - https://github.com/dapr/rust-sdk/milestone/1
Dashboard - https://github.com/dapr/dashboard/milestone/8
Quickstarts (aka Tutorials) - https://github.com/dapr/quickstarts/milestone/10

**Comment by shubham1172** [comment]
JavaScript SDK milestone https://github.com/dapr/js-sdk/milestone/15

**Comment by m3nax** [comment]
I think the dotnet SDK milestone is: https://github.com/dapr/dotnet-sdk/milestone/19

**Comment by mikeee** [comment]
> 19

Indeed it is, thanks for reminding!

**Comment by thewilli** [comment]
Could you please also consider adding #7774 here? It is tagged with the v1.14 milestone but not mentioned here at all.

**Comment by mikeee** [comment]
> Could you please also consider adding #7774 here? It is tagged with the v1.14 milestone but not mentioned here at all.

Any items tagged with a milestone don't necessarily mean they should be added to this release tracker. I do think that this issue if addressed should be included in the release/backported if possible. I've added it to the not-prioritized/non-blocking list.

@thewilli Are you working on a PR for this issue?

**Comment by berndverst** [comment]
Redis Azure support completed and now available in contrib `v1.14.0-rc.3`

**Comment by panagiotiskompis** [comment]
Is there an estimate for the RC Release day?

**Comment by mikeee** [comment]
The RC was released yesterday 🚀 

https://github.com/dapr/dapr/releases/tag/v1.14.0-rc.1

**Comment by m3nax** [comment]
When will 1.14 be released?

**Comment by panagiotiskompis** [comment]
1.14 will still mark the Workflow building block as beta?

**Comment by yaron2** [comment]
> 1.14 will still mark the Workflow building block as beta?

Yes. 1.15 is when it's slated to go stable.
