### ISSUE TITLE
v1.13.2 Checklist

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#7673]
- [x] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
    - [ ] Security vulnerability
        - <>
    - [x] Regression that does not have a work around:
        - <>
    - [ ] Broken mainline scenario that has a missing test case:
        - <>
- [x] Create Tag
    - [x] <>
- [x] Performance tests passing
- [x]  End to End tests passing on Linux and Windows
- [x]  New test case written to catch future occurrences
- [x]  Notify users to try RC (Announce on Discord Announcements channel)
    - [x] <>
- [ ]  Update the longhaul tests to use RC
    - [ ] <>
- [x]  Write release notes
    - [x] <>
- [x]  Review release notes [@dapr/maintainers-dapr]
- [x]  Create Tag [@dapr/maintainers-dapr]
- [ ]  Backport fixes into master branch [@dapr/maintainers-dapr]
- [ ]  Update the documentation: Latest version & versions in supported releases
- [ ]  Push new tag in installer-bundle repo
- [x]  Announce the patch release on Discord Announcements channel
