### ISSUE TITLE
1.13.3 Patch Release Checklist

### ISSUE THREAD

**Issue by elena-kolevska** [dapr/dapr#7750]
- [ ] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
    - [X] Security vulnerabilities
        - [Prevent App API token from being forwarded from caller to receiving app](https://github.com/dapr/dapr/commit/e0591e43d0cdfd30a2f2960dce5d9892dc98bc2c)
        - [Upgrade Go version to 1.21.9]()
    - [X] Regression that does not have a workaround:
        - https://github.com/dapr/dapr/issues/7642
    - [X] Broken mainline scenario that has a missing test case:
        - https://github.com/dapr/dapr/issues/7031
- [ ] Performance tests passing
- [ ]  End to End tests passing on Linux and Windows
- [x]  New test case written to catch future occurrences
- [x]  Update the longhaul tests to use RC (@elena-kolevska ) https://github.com/dapr/test-infra/pull/223
- [x]  Write release notes
- [x]  Review release notes [@dapr/maintainers-dapr]
- [x]  Create Tag 1.13.3 [@dapr/maintainers-dapr] https://github.com/dapr/dapr/releases/tag/v1.13.3
- [ ]  Backport fixes into master branch [@dapr/maintainers-dapr]
- [x]  Update the documentation: Latest version & versions in supported releases (@elena-kolevska https://github.com/dapr/docs/pull/4156 )
- [ ]  Push new tag in installer-bundle repo
- [x]  Announce the patch release on Discord Announcements channel
