### ISSUE TITLE
Milestone 0.2.0 Endgame

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#785]
This is the endgame schedule for milestone 0.2.0 release

## Schedule

End game master: @yaron2  
End game buddy: @msfussell

This is the schedule for 0.2.0 Release

## Schedule

11/14  **10am** PST code freeze for the release
11/15 Release date

- [x] Code freeze at 10am 11/14
- [x] Test and validate the release - run through samples, demos, review docs, E2E tests, manual testing, @yaron2 @shalabhms @youngbupark 
- [x] Test and validate the .NET SDK release - run through samples, @shalabhms 
- [x] Manually upload Nuget packages. - @shalabhms 
- [x] Create 0.2.0 release branches for Dapr runtime @youngbupark 
- [x] Create 0.2.0 release branches for CLI @youngbupark 
- [x] Create 0.2.0-preview01 .NET SDK @youngbupark 
- [x] Create release notes - CLI, Dapr and .NET SDK @yaron2 @shalabhms 
       https://github.com/dapr/dapr/tree/master/docs/release_notes
- [x] Create a release candidate and tag @youngbupark 
- [x] Release runtime images to Docker Hub @youngbupark 
- [x] Release sample Docker images to GitHub artifacts @youngbupark 
- [x] Fix bugs
- [x] Create 0.2.0 tag for docs and samples in the repos.
- [x] Complete final build and release
- [x] Scrubbed version of Ignite Dapr deck @AaronCrawfis 
- [x] Announcement email and Twitter post
