### ISSUE TITLE
Minor Patch Release Checklist

### ISSUE THREAD

**Issue by mikeee** [dapr/dapr#7862]
## Release team
Release lead: @mikeee
Release lead shadow(s):
Perf test lead: @cicoyle
Longhaul test: @elena-kolevska
Build manager: @JoshVanL

Read about the [Dapr release lifecycle](https://github.com/dapr/community/blob/master/release-process.md)

Feature definition starts: 2024-03-12
Feature definition ends: 2024-03-26
Feature freeze: 2024-05-28
Code freeze (Endgame starts ~2 weeks stabilization): 2024-06-25
Release day: ~2024-07-09~ TBC
Announcement day: TODO

Release Tasks:
------------------
- [x] Code freeze at : 2024-06-25
- [ ] Remaining Changes for 1.14:
  - [ ] 

- [ ] Docs:
  - [ ]

- [ ] SDKs:
  - [ ]

- [ ] Quickstarts:
  - [ ]

---
- [ ] Check all new components are registered in dapr/dapr @mikeee 
- [ ]  E2E, certification and perf tests are passing @cicoyle 
- [ ] Create release-1.14 branch and cut RC 1.14.0-rc.1 for component-contrib @berndverst 
- [ ] Update dapr/component-contrib pkg to 1.14.0-rc.1 in dapr/dapr master branch @cicoyle 
- [ ] Create release-1.14 branch for Dapr runtime @JoshVanL 
- [ ] Verify helm chart and cut the 1.14.0-rc.1 release for Dapr runtime @JoshVanL 
- [ ] Create release-1.14 branch for CLI @mikeee
- [ ] Update dapr/dapr pkg to 1.14.0-rc.1 in dapr/cli release-1.14 branch @mikeee 
- [ ] Cut the 1.14.0-rc.1 release for CLI @yaron2 
- [ ] Trigger GitHub actions in dapr/homebrew-tap (GitHub disables Actions after 1mo without commits) @artursouza 
- [ ] Notify users about dapr/dapr 1.14.0-rc.1 via Discord @mikeee 
- [ ] Validate the upgrade path from the previous release -- CRDs updated, no deletion of components/configs etc. @elena-kolevska 
- [ ] Create RC for installer-bundle @mikeee 
- [ ] Validate RC for installer bundle @mikeee
- [ ] Update proto and cut the rc release for Java SDK @artursouza 
- [ ] Update proto for Python SDK @berndverst 
- [ ] Update proto for Go SDK @yaron2 
- [ ] Update proto and cut the rc release for dotnet SDK @artursouza 
- [ ] Update proto cpp SDK @artursouza 
- [ ] Update proto for rust SDK @mikeee 
- [ ] Cut the rc release for Dashboard @dapr/maintainers-dashboard 
- [ ] Update longhaul tests with RC for runtime and dotnet SDK @elena-kolevska 
- [ ] Update quickstarts/tutorials automated validation and check it works - covers Linux Standalone/ K8s / Darwin MacOS. @dapr/maintainers-quickstarts 
- [ ] Create PR for quickstarts to point to RC SDKs/Dev package? if it is available @dapr/maintainers-quickstarts 
- [ ] Test and validate tutorials in Linux ARM64 k8s and self-hosted @dapr/maintainers-quickstarts 
- [ ] Test and validate tutorials in Windows @dapr/maintainers-quickstarts 
- [ ] Validate Dapr CLI non-slim scenarios on Windows @mikeee 
- [ ] Validate Multi app run K8s on Windows @mikeee 
- [ ] Validate longhaul metrics  @elena-kolevska 
- [ ] Test and validate the .NET SDK - run through samples @dapr/maintainers-dotnet-sdk 
- [ ] Test and validate the Java SDK - run through samples @dapr/maintainers-java-sdk 
- [ ] Test and validate the Python SDK - run through samples @dapr/maintainers-python-sdk 
- [ ] Test and validate the Go SDK - run through samples @mikeee 
- [ ] Test and validate Dashboard, local mode and kubernetes hosted @mikeee 
- [ ] Update certification tests in components-contrib release branch (prior to merge back into master) to use the RC (and Go SDK RC/release if possible). @mikeee 
- [ ] Confirm with maintainers that each repo has milestone set for all relevant issues & PRs, then generate release notes
  - [ ] CLI
  - [ ] runtime
  - [ ] components-contrib
  - [ ] .NET SDK
  - [ ] Java SDK
  - [ ] JS SDK
  - [ ] Python SDK
  - [ ] Go SDK
  - [ ] Check all milestones for each repo above are up to date before cutting the release notes.
- [ ] Validate FOSSA on each repo 
  - [ ] CLI
  - [ ] runtime
  - [ ] components-contrib
  - [ ] .NET SDK
  - [ ] Java SDK
  - [ ] ~JS SDK~ 
  - [ ] Python SDK
  - [ ] Go SDK
- [ ] Edit and complete release-notes on HackMD (everyone)
- [ ] Verify 1.14 documentation

ETA for all above: ~ 
------------------
RELEASE DAY:

- [ ] ~Release Dashboard~
- [ ] Validate breaking changes section in release notes (everyone)
- [ ] Merge release notes into release branch
- [ ] Cut tag for components-contrib
- [ ] Release Dapr 1.14
- [ ] Release CLI 1.14
- [ ] Validate CLI release locations:
  - [ ] Chocolatey
  - [ ] Winget
  - [ ] Brew
- [ ] Release Installer Bundle 1.14
- [ ] Create blog post
- [ ] Release cpp-sdk
- [ ] Release js-sdk
- [ ] Release go-sdk
- [ ] Release java-sdk
- [ ] Release python-sdk
- [ ] Release rust-sdk
- [ ] Release dotnet-sdk and release nuget packages
- [ ] Create release-1.14 branch for quickstarts, update version tag in the images, create v1.14.0 tag
- [ ] Create components-contrib release from Tag. Copy components release notes section into the description of the release.
- [ ] Validate DevContainers in following repos
  - [ ] dapr/dapr
  - [ ] dapr/components-contrib
  - [ ] dapr/cli
  - [ ] dapr/quickstarts
- [ ] Update certification tests in components-contrib release branch (prior to merge back into master) to use latest runtime and Go SDK release.
- [ ] Generate new Java docs based on the release version of the Java SDK

------------------
POST RELEASE DAY
- [ ] Update Dapr K8s Operator https://operatorhub.io/operator/dapr-kubernetes-operator
- [ ] Update Dapr Kratix Marketplace https://github.com/syntasso/kratix-marketplace/tree/main/dapr
- [ ] Update Dapr Test Containers Module https://github.com/diagridio/testcontainers-dapr

**Comment by elena-kolevska** [comment]
## Validating the upgrade path from the previous release

**Findings:**
- Upgrade works as expected
- New configurations: `excludeVerbs`, `pathMatching`, `latencyDistributionBuckets`
- New scheduler pod, service and stateful set
- Legacy port 80 was removed from the Sentry service

**Process:**
- `dapr init --kubernetes`
- `dapr status -k`
- Create a new temp dir:
    
    ```python
    mkdir ~/Desktop/temp
    cd ~/Desktop/temp
    git init
    ```
    
- Export definitions:
    
    ```bash
    kubectl get crd -o yaml  > ~/Desktop/temp/dapr-crds.yaml
    kubectl get cm -n dapr-system -o yaml > ~/Desktop/temp/dapr-configmaps.yaml
    kubectl get all -n dapr-system -o yaml > ~/Desktop/temp/getall.md
    ```
    
- Commit the changes in the temp dir, so we can compare them later against 1.14
- Upgrade to latest dapr
    
    ```bash
    dapr uninstall --kubernetes
    dapr init --runtime-version 1.14.0-rc.2 --kubernetes
    dapr -v
    ```
    
- Check status
    
    ```bash
    dapr status -k
    ```
    
- Export the definitions again:
    
    ```bash
    kubectl get crd -o yaml  > ~/Desktop/temp/dapr-crds.yaml
    kubectl get cm -n dapr-system -o yaml > ~/Desktop/temp/dapr-configmaps.yaml
    kubectl get all -n dapr-system -o yaml > ~/Desktop/temp/getall.md
    ```
    
- Check the git diff in the `temp` directory and see if everything has been updated as expected
    
    ```bash
    git diff > 1.13-to-1.14.diff
    ```

**Comment by elena-kolevska** [comment]
PR for updating longhaul release version: https://github.com/dapr/test-infra/pull/227
Ping @mikeee .
