### ISSUE TITLE
[Tracking issue] Dapr Workflows Stable 

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#8008]
This issue will be the source of truth for collating all tasks what must be complete in order for Workflows to progress to Stable, for the 1.15 release.

## Dapr Runtime / durabletask-go

- [ ] [P0] Scheduler moving to being the default, [tracking issue here](https://github.com/dapr/dapr/issues/7796)
  - [ ] Migration - State -> Scheduler reminders
- [x] [P0] https://github.com/dapr/dapr/issues/8085
- [x] [P0] https://github.com/dapr/dapr/issues/7749
- [x] [P0] https://github.com/dapr/dapr/issues/6889
- [x] [P0] https://github.com/dapr/dapr/issues/7777
- [ ] [P0] https://github.com/dapr/dapr/issues/7824
- [x] [P0] https://github.com/dapr/dotnet-sdk/issues/1205
- [ ] [P0] https://github.com/dapr/dapr/issues/8277
- [ ] [P1] https://github.com/dapr/dapr/issues/7927
- [ ] [P1] https://github.com/dapr/dapr/issues/6014
- [ ] [P1] https://github.com/dapr/dapr/issues/7633
- [ ] [P2] https://github.com/dapr/dapr/issues/7934
- [ ] [P2] https://github.com/dapr/dapr/issues/7706
- [ ] [P2] https://github.com/dapr/dapr/issues/8088

## Contrib / State Store
- [ ] [P0] [AzureSQL] https://github.com/dapr/dapr/issues/7570

## Quickstarts

- [x] https://github.com/dapr/dotnet-sdk/issues/1234

## Perf

- [ ] 

## Docs

- [ ] https://github.com/dapr/dapr/issues/6475

### .NET SDK

- [x] [P0] https://github.com/dapr/dotnet-sdk/issues/1344
- [ ] [P0] https://github.com/dapr/dotnet-sdk/issues/1293
- [ ] [P0] https://github.com/dapr/dapr/issues/8086
- [ ] [P0] https://github.com/dapr/dotnet-sdk/issues/1216
- [x] [P0] https://github.com/dapr/dotnet-sdk/issues/1215
- [x] [P0] https://github.com/dapr/dotnet-sdk/issues/1203
- [x] [P0] https://github.com/dapr/dotnet-sdk/issues/1163 (also requires runtime work)
- [ ] [P1] https://github.com/dapr/dotnet-sdk/issues/1118
- [ ] [P1] https://github.com/dapr/dotnet-sdk/issues/1220
- [ ] [P1] https://github.com/dapr/dotnet-sdk/issues/1200
- [x] [P1] https://github.com/dapr/dotnet-sdk/pull/1244 (PR that needs to be reviewed/merged)
- [ ] [P2] https://github.com/dapr/dotnet-sdk/issues/1225

### Java SDK

- [ ] [P????] https://github.com/dapr/java-sdk/issues/1155
- [ ] [P0] https://github.com/dapr/java-sdk/issues/1012
- [ ] [P1] https://github.com/dapr/java-sdk/issues/991
- [ ] [P1] https://github.com/dapr/java-sdk/issues/980
- [ ] [P1] https://github.com/dapr/java-sdk/issues/966
- [ ] [P1] https://github.com/dapr/java-sdk/issues/905

### JavaScript SDK / durabletask_js - _thank you @famarting_ 

- [x] https://github.com/dapr/js-sdk/issues/643
- [x] https://github.com/microsoft/durabletask-js/issues/64 (requires counterpart change in dapr sdk)
- [ ] https://github.com/microsoft/durabletask-js/issues/47 (requires counterpart change in dapr sdk)
- [ ] https://github.com/microsoft/durabletask-js/issues/30 (requires counterpart change in dapr sdk)
- [ ] https://github.com/microsoft/durabletask-js/issues/13 (requires counterpart change in dapr sdk)
- [x] https://github.com/dapr/js-sdk/issues/638
- [x] https://github.com/dapr/js-sdk/issues/639

### Go SDK - _thank you @famarting_ 

- [ ] https://github.com/dapr/go-sdk/issues/611
- [x] https://github.com/dapr/go-sdk/issues/541
- [x] https://github.com/dapr/go-sdk/issues/634
- [x] https://github.com/dapr/go-sdk/issues/493
- [x] https://github.com/dapr/go-sdk/issues/497
- [x] https://github.com/dapr/go-sdk/issues/635
- [ ] https://github.com/dapr/go-sdk/issues/636
- [x] https://github.com/microsoft/durabletask-go/pull/83

### Python SDK - _thank you @famarting_

- [x] https://github.com/dapr/python-sdk/issues/655
- [x] https://github.com/dapr/python-sdk/issues/738
- [x] https://github.com/dapr/python-sdk/issues/739
- [x] https://github.com/dapr/python-sdk/issues/740
- [x] https://github.com/dapr/python-sdk/issues/711

**Deferred / Not essential for Stable** 
- https://github.com/dapr/dapr/issues/3417
- [CosmosDb] https://github.com/dapr/dapr/issues/7321
- https://github.com/dapr/dapr/issues/8243
- https://github.com/dapr/java-sdk/issues/1156
- https://github.com/dapr/python-sdk/issues/748
- ~~https://github.com/microsoft/durabletask-python/issues/32~~
- https://github.com/dapr/durabletask-python/issues/4
- https://github.com/dapr/js-sdk/issues/657 (requires counterpart change in dapr/durabletask-js)

**Comment by arturotrenard** [comment]
Hello, this keeps happening.  https://github.com/dapr/dapr/issues/7824

**Comment by mikeee** [comment]
@olitomlinson I don't want to modify the issue directly but - https://github.com/dapr/dapr/issues/3417 appears to be unrelated to getting workflows to stable.

**Comment by mikeee** [comment]
@dapr/approvers-dotnet-sdk @dapr/maintainers-dotnet-sdk  - Are all of these SDK issues proportionate, necessary, appropriate and is there bandwidth to get them completed for workflows to be stable?

**Comment by olitomlinson** [comment]
@mikeee I wasn't clear btw, I fully expect the above list to be triaged for suitability by the maintainers for what is in and out of scope for 1.15 :)

**Comment by mikeee** [comment]
> @mikeee I wasn't clear btw, I fully expect the above list to be triaged for suitability by the maintainers for what is in and out of scope for 1.15 :) 
> 

Thought so, I'll await the dotnet-sdk maintainers to triage the SDK items

**Comment by cgillum** [comment]
I'll be helping out with the triage of these items over the next few days.

**Comment by cgillum** [comment]
@olitomlinson I think https://github.com/dapr/dapr/issues/3417 might be referring to GitHub actions workflows and not Dapr Workflow. If you agree, then we can probably take it off this list.

**Comment by cicoyle** [comment]
I went ahead and added [P_] next to the above issues for us to better see what work is a P0 for this release

**Comment by famarting** [comment]
@olitomlinson @cgillum I'll be going through the go, python and javascript SDKs to review the different changes we need pursuing SDK parity and workflows to become stable

So far this is a list of issue for the go sdk that I believe should be tracked here:

- [ ] https://github.com/dapr/go-sdk/issues/611
- [ ] https://github.com/dapr/go-sdk/issues/541
- [ ] https://github.com/dapr/go-sdk/issues/634
- [ ] https://github.com/dapr/go-sdk/issues/493
- [ ] https://github.com/dapr/go-sdk/issues/497
- [ ] https://github.com/microsoft/durabletask-go/issues/42
- [ ] https://github.com/dapr/go-sdk/issues/635
- [ ] https://github.com/dapr/go-sdk/issues/636

**Comment by famarting** [comment]
Here are the issues for the python SDK

- [ ] https://github.com/dapr/python-sdk/issues/655
- [ ] https://github.com/dapr/python-sdk/issues/738
- [ ] https://github.com/dapr/python-sdk/issues/739
- [ ] https://github.com/dapr/python-sdk/issues/740
- [ ] https://github.com/dapr/python-sdk/issues/711

**Comment by famarting** [comment]
And the js sdk issues, the durabletask-js issues would need their counterpart issues created in the js-sdk repo:

- [ ] https://github.com/microsoft/durabletask-js/issues/64
- [ ] https://github.com/microsoft/durabletask-js/issues/47
- [ ] https://github.com/microsoft/durabletask-js/issues/30
- [ ] https://github.com/microsoft/durabletask-js/issues/13
- [ ] https://github.com/dapr/js-sdk/issues/638
- [ ] https://github.com/dapr/js-sdk/issues/639

**Comment by WhitWaldo** [comment]
@olitomlinson The top P0 item in the .NET SDK referencing https://github.com/dapr/dotnet-sdk/issues/1344 can be marked off as completed

**Comment by cgillum** [comment]
Added prioritized list of Java SDK issues to the OP.

**Comment by olitomlinson** [comment]
I've discovered that the workflow SDKs are inconsistent in the naming of `callChildWorkflow` / `callSubWorkflow`

- `dotnet`, `go`,  and `python` use `callChildWorkflow`
- `java` and `javascript` use `callSubWorkflow` 

I believe the SDKs should strive for consistency where sensible, and should strive to be consistent with the [docs](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/#child-workflows) which only refers to _child workflows_

I've raised tickets to bring the Java and JS SDKs inline with the others :

- https://github.com/dapr/java-sdk/issues/1155
- https://github.com/dapr/js-sdk/issues/643

I believe these would both be considered P0 as we want to go into the Stable release with method names that won't change.

Thoughts @yaron2 @artursouza ?

**Comment by olitomlinson** [comment]
> @olitomlinson I'd like to propose adding #7321 to the stabilization list as it's a named issue on the [Workflow Limitations](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#limitations), but the issue was closed due to staleness.

I agree. I've reopened this and added this to the main list.

@cgillum what priority should be attached to this item? Are we intending to ship with CosmosDb support in 1.15?

**Comment by cgillum** [comment]
@olitomlinson per an earlier discussion with @yaron2, I think the best path forward is to have a list of supported state stores for workflow, similar to actors (it would necessarily be a subset of actor state stores). Cosmos DB and similar state stores would *not* be on that list due to the issue you linked to. Unfortunately, I think there isn't enough time to work through those issues before Stable.

**Comment by WhitWaldo** [comment]
@cgillum Is there an issue somewhere that tracks progress of the NoSQL support and what's lacking?

**Comment by cgillum** [comment]
@WhitWaldo I don't believe we have an issue tracking progress of this work. However, I do have an old PR that does the foundational work in the `durabletask-go` dependency to enable it: https://github.com/microsoft/durabletask-go/pull/50 ("state update chunking"). The main problem has been finding the time to validate and stabilize it.

**Comment by WhitWaldo** [comment]
@olitomlinson Possible additions to the list following the discussion in #Workflow by @NunzioCar:

https://github.com/dapr/dapr/issues/8322
https://github.com/dapr/dapr/issues/8323
