### ISSUE TITLE
v1.15 Release Planning

### ISSUE THREAD

**Issue by mikeee** [dapr/dapr#8017]
[Release Tracking Board](https://github.com/orgs/dapr/projects/87)

Release lead: @mikeee 
Release lead shadow(s): -
Perf test lead: @cicoyle 
Longhaul test: @elena-kolevska 
Build manager: @JoshVanL 

Read about the [Dapr release lifecycle](https://github.com/dapr/community/blob/master/release-process.md)

## Milestone dates

- [x] Feature definition starts: 27th August 2024 (27/08/2024)
- [x] Feature definition ends: 10th September 2024 (10/09/2024)
- [x] Feature freeze: 29th October 2024 (29/10/2024)
- [x] Code freeze (Endgame starts ~1-2 weeks stabilization):  26th November 2024 (26/11/2024)
- [x] RC Release day: 20th January 2025 (26/11/2024)
- [x] Release day: 05th February 2025 (05/02/2025)
- [x] Announcement day: 05/02/2025 < - Docs, Samples and Runtime, CLI, Release notes

## Priorities/themes for this release

- [x] [P0] [Workflow API to stable including SDKs](https://github.com/dapr/dapr/issues/8008) @cgillum / @yaron2
- [x] [P0] [Conversation API](https://github.com/dapr/proposals/pull/59) (Alpha) @daixiang0 
  - [x] Docs - @msfussell 
  - [x] SDK (Go) - Issue: https://github.com/dapr/go-sdk/issues/645 - @mikeee 
  - [x] SDK (Rust) - Issue: https://github.com/dapr/rust-sdk/issues/233 - @mikeee 
  - [x] SDK (.NET) - https://github.com/dapr/dotnet-sdk/pull/1382
- [x] [P0] Test stabilization in Dapr runtime/CLI/SDKs
  - [x] Runtime @JoshVanL 
  - [x] CLI @antontroshin 
    - [x]  https://github.com/dapr/cli/pull/1450
  - [x] SDKs
    - [x] Java - @cicoyle 
    - [x] JS ?
    - [x] .NET - @dapr/maintainers-dotnet-sdk 
    - [x] Go - @mikeee
    - [x] Python - @dapr/maintainers-python-sdk 
    - [x] Rust - @mikeee 
  - [x] Components-Contrib 
- [x] [P0] bi-directional subscription
  - [x] [P0] Python SDK @elena-kolevska - https://github.com/dapr/python-sdk/issues/730
  - [x] [P0] .Net SDK @WhitWaldo - https://github.com/dapr/dotnet-sdk/pull/1381
  - [x] [P1] Java SDK @artursouza - https://github.com/dapr/java-sdk/issues/1072
  - [x] ~~[P1] https://github.com/dapr/docs/issues/4424~~ -> 1.16
- [x] [P0] HTTP Status code config for resiliency @antontroshin  - https://github.com/dapr/dapr/pull/8252
- [x] [P0] Error code in metrics @antontroshin - https://github.com/dapr/dapr/pull/8256
  - [x] proposal https://github.com/dapr/proposals/pull/67  
- [x] [P0] [Scheduler __service__ to stable](https://github.com/dapr/dapr/issues/7796) @cicoyle 
  - [x] metrics
  - [x] namespace controller
  - [x] reminder data migration
  - [x] https://github.com/dapr/test-infra/pull/238

For all items being tracked in this release, refer to the [Release Tracking Board](https://github.com/orgs/dapr/projects/87)

## Moved to v1.16
- [P1] Add support for metrics and logging in OpenTelemetry Integration
- [P1] (Streaming subscription examples) https://github.com/dapr/docs/issues/4424
- [P1] SDK Resiliency proposal implemented
- [P1] Design approval for KV List @elena-kolevska 
## Repo milestones

Dapr - https://github.com/dapr/dapr/milestone/22
CLI - https://github.com/dapr/cli/milestone/16
Docs - https://github.com/dapr/docs/milestone/18
Components-contrib - https://github.com/dapr/components-contrib/milestone/16
Java-SDK -  https://github.com/dapr/java-sdk/milestone/13
Python-SDK -  https://github.com/dapr/python-sdk/milestone/17
Dotnet-SDK - https://github.com/dapr/dotnet-sdk/milestone/20
Js-SDK - https://github.com/dapr/js-sdk/milestone/17
Go-SDK - https://github.com/dapr/go-sdk/milestone/12
Rust-SDK - https://github.com/dapr/rust-sdk/milestone/2
Dashboard - https://github.com/dapr/dashboard/milestone/9
Quickstarts (aka Tutorials) - https://github.com/dapr/quickstarts/milestone/11

**Comment by WhitWaldo** [comment]
@mikeee Small tweak - the Jobs API PR you cited is for the Jobs block, not the bidirectional subscription capability. I have a separate [draft PR here](https://github.com/dapr/dotnet-sdk/pull/1346) for that one that's a draft while I finish up examples + tests.

**Comment by mikeee** [comment]
> @mikeee Small tweak - the Jobs API PR you cited is for the Jobs block, not the bidirectional subscription capability. I have a separate [draft PR here](https://github.com/dapr/dotnet-sdk/pull/1346) for that one that's a draft while I finish up examples + tests.

Indeed, it was raised that the sub-item (jobs pr) listed is a dependency of pushing forward the bidi pubsub implementation.

**Comment by WhitWaldo** [comment]
It'd be ideal - @philliphoff and I had a chat a while ago in favor of splitting out some of the common .NET functionality into separate projects (e.g. prototypes, client construction, exceptions, etc.) and both PRs take a step towards accomplishing that. Frankly, when one is accepted, I'll make some tweaks to the other PR to accommodate, so if both are expected for 1.15, feel free to take either one first and I'll make the necessary updates to the other.

**Comment by WhitWaldo** [comment]
- The bidirectional subscription work has been merged in .NET and can be checked off.
- I don't see it listed, but Job has also been merged
- Conversations is under review
