### ISSUE TITLE
1.14.4 Patch Release Checklist

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#8111]
- [x] Dapr maintainer(s) communicate out the discovery of issues that require a patch release and the reason why to the Discord Maintainers and Release channels. Patch releases are made for one of categories below:
    - [x] Regression that does not have a work around:
        - Upgrade to 1.14.3 fails due to change in scheduler's statefulset: https://github.com/dapr/dapr/pull/8108
        - Fixes connectivity issue on placement leadership change: https://github.com/dapr/dapr/pull/8105
- [x] Create RC Tag
- [ ] ~Performance tests passing~
- [x]  End to End tests passing on Linux and ~Windows~
- [ ]  ~New test case written to catch future occurrences~ To be done in master branch
- [ ]  ~Notify users to try RC (Announce on Discord Announcements channel)~
- [ ]  ~Update the longhaul tests to use RC~
- [x]  Write release notes
- [x]  Review release notes [@dapr/maintainers-dapr]
- [ ]  Create Tag [@dapr/maintainers-dapr]
- [ ]  Backport fixes into master branch [@dapr/maintainers-dapr]
- [ ]  Update the documentation: Latest version & versions in supported releases
- [ ]  Push new tag in installer-bundle repo
- [ ]  Announce the patch release on Discord Announcements channel

**Comment by cicoyle** [comment]
1.14.4 is released, so closing this
