### ISSUE TITLE
Windows node support in Kubernetes

### ISSUE THREAD

**Issue by aidapsibr** [dapr/dapr#842]
## In what area(s)?

> /area runtime
> /area operator
/area placement
> /area docs
> /area test-and-release

## Describe the feature
I would like to utilize dapr on .NET framework applications that have been lift-and-shifted, but will talk to Linux micro-services via dapr. Currently, if I understand correctly, the sidecar injector has no context to distinguish if a pod is on a Windows or Linux node. I can currently create a Windows dapr image and configure that in my cluster, but then my cluster would not support Linux.

**Comment by yaron2** [comment]
Correct, the sidecar injector takes a single image of the `daprd` runtime and injects it to any pod.

Would an ad-hoc solution targeting Windows be enough (for example, provide an additional ENV var to the injector for a Windows image and then add a Dapr annotation on the Pod spec like `dapr.io/windows`?

**Comment by psibernetic** [comment]
I think so, I'm looking into making a nanoserver image for dapr for this case, pretty new to this toolchain though.

**Comment by amanbha** [comment]
This is to support windows containers on k8s.Changes needed: a windows container image for daprd and changes in injector to inject correct image based on platform.

**Comment by youngbupark** [comment]
@msfussell @orizohar there is another customer (@Phiph) who wants to run dapr on windows. We have already generated Windows binaries. But we have not built windows container images and validate it properly. I think in the community call, we can ask the needs of windows cluster support. 

Most of work will be the engineering tool change and validation. the work size will be 1 week for 1 engineer, including validation.

**Comment by asumner** [comment]
> @msfussell @orizohar there is another customer (@Phiph) who wants to run dapr on windows. We have already generated Windows binaries. But we have not built windows container images and validate it properly. I think in the community call, we can ask the needs of windows cluster support.
> 
> Most of work will be the engineering tool change and validation. the work size will be 1 week for 1 engineer, including validation.
Any update?
I need this also, we are locked (for now) in .Net Framework services but I suspect many  app modernization programmes will also need windows container support. Dapr isn't platform? agnostic  if its all linux? So please provide guidance on the status, if there is a manual build process can we get some docs to help us create the windows binaries? Thanks, we look forward to using Dapr :)

**Comment by youngbupark** [comment]
@msfussell @orizohar as we discussed before, I marked this issue as one of work item of 0.9.0 release. 

cc/ @yaron2 @amanbha

**Comment by youngbupark** [comment]
We need to write up the specs for the below scenarios:
1. Deploy dapr control plane to linux nodes and deploy apps to windows and linux nodes
2. Deploy dapr control plane to windows nodes and deploy apps to windows and linux nodes

Expected work items: 
- [ ] Create Windows docker image and push them to dockerhub
- [ ] Build CI pipeline for windows docker image
- [ ] inject windows dapr image by Checking `nodeSelector` in deployment yaml - https://docs.microsoft.com/en-us/azure/aks/windows-container-cli#run-the-application
- [ ] Expand E2E test environment to Windows node.

**Comment by wcs1only** [comment]
All subtasks are done. Closing epic.
